
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20150326 (SVN rev 63)
//----------------------------------------------------

import java_cup.runtime.Symbol;
import java_cup.runtime.XMLElement;

/** CUP v0.11b 20150326 (SVN rev 63) generated parser.
  */
@SuppressWarnings({"rawtypes"})
public class CMinusParser extends java_cup.runtime.lr_parser {

 public final Class getSymbolContainer() {
    return Sym.class;
}

  /** Default constructor. */
  @Deprecated
  public CMinusParser() {super();}

  /** Constructor which sets the default scanner. */
  @Deprecated
  public CMinusParser(java_cup.runtime.Scanner s) {super(s);}

  /** Constructor which sets the default scanner. */
  public CMinusParser(java_cup.runtime.Scanner s, java_cup.runtime.SymbolFactory sf) {super(s,sf);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\077\000\002\002\004\000\002\002\003\000\002\003" +
    "\004\000\002\003\003\000\002\004\003\000\002\004\003" +
    "\000\002\005\005\000\002\005\010\000\002\007\003\000" +
    "\002\007\003\000\002\006\010\000\002\010\003\000\002" +
    "\010\003\000\002\011\005\000\002\011\003\000\002\012" +
    "\004\000\002\012\006\000\002\013\006\000\002\014\004" +
    "\000\002\014\002\000\002\015\004\000\002\015\002\000" +
    "\002\016\003\000\002\016\003\000\002\016\003\000\002" +
    "\016\003\000\002\016\003\000\002\017\004\000\002\017" +
    "\003\000\002\020\007\000\002\020\011\000\002\021\007" +
    "\000\002\022\004\000\002\022\005\000\002\023\005\000" +
    "\002\023\003\000\002\024\003\000\002\024\006\000\002" +
    "\025\005\000\002\025\003\000\002\026\003\000\002\026" +
    "\003\000\002\026\003\000\002\026\003\000\002\026\003" +
    "\000\002\026\003\000\002\027\005\000\002\027\003\000" +
    "\002\030\003\000\002\030\003\000\002\031\005\000\002" +
    "\031\003\000\002\032\003\000\002\032\003\000\002\033" +
    "\005\000\002\033\003\000\002\033\003\000\002\033\003" +
    "\000\002\034\006\000\002\035\003\000\002\035\002\000" +
    "\002\036\005\000\002\036\003" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\146\000\006\031\013\035\010\001\002\000\004\002" +
    "\150\001\002\000\010\002\ufffc\031\ufffc\035\ufffc\001\002" +
    "\000\010\002\ufffd\031\ufffd\035\ufffd\001\002\000\010\002" +
    "\000\031\013\035\010\001\002\000\004\004\ufff8\001\002" +
    "\000\004\004\014\001\002\000\010\002\ufffe\031\ufffe\035" +
    "\ufffe\001\002\000\004\004\ufff9\001\002\000\010\006\017" +
    "\012\016\027\015\001\002\000\032\002\ufffb\004\ufffb\005" +
    "\ufffb\006\ufffb\010\ufffb\011\ufffb\027\ufffb\031\ufffb\033\ufffb" +
    "\034\ufffb\035\ufffb\036\ufffb\001\002\000\004\005\144\001" +
    "\002\000\006\031\013\035\021\001\002\000\006\007\ufff6" +
    "\030\142\001\002\000\006\004\ufff8\007\ufff5\001\002\000" +
    "\004\004\137\001\002\000\004\007\025\001\002\000\006" +
    "\007\ufff3\030\ufff3\001\002\000\004\010\026\001\002\000" +
    "\030\004\uffee\005\uffee\006\uffee\010\uffee\011\uffee\027\uffee" +
    "\031\uffee\033\uffee\034\uffee\035\uffee\036\uffee\001\002\000" +
    "\010\002\ufff7\031\ufff7\035\ufff7\001\002\000\030\004\uffec" +
    "\005\uffec\006\uffec\010\uffec\011\uffec\027\uffec\031\013\033" +
    "\uffec\034\uffec\035\010\036\uffec\001\002\000\024\004\044" +
    "\005\045\006\043\010\026\011\046\027\035\033\042\034" +
    "\040\036\037\001\002\000\030\004\uffef\005\uffef\006\uffef" +
    "\010\uffef\011\uffef\027\uffef\031\uffef\033\uffef\034\uffef\035" +
    "\uffef\036\uffef\001\002\000\004\004\034\001\002\000\006" +
    "\012\016\027\015\001\002\000\026\004\uffe5\005\uffe5\006" +
    "\uffe5\010\uffe5\011\uffe5\027\uffe5\032\uffe5\033\uffe5\034\uffe5" +
    "\036\uffe5\001\002\000\024\004\uffed\005\uffed\006\uffed\010" +
    "\uffed\011\uffed\027\uffed\033\uffed\034\uffed\036\uffed\001\002" +
    "\000\004\006\133\001\002\000\012\004\044\005\045\006" +
    "\043\027\131\001\002\000\026\004\uffea\005\uffea\006\uffea" +
    "\010\uffea\011\uffea\027\uffea\032\uffea\033\uffea\034\uffea\036" +
    "\uffea\001\002\000\004\006\122\001\002\000\010\004\044" +
    "\005\045\006\043\001\002\000\044\006\107\007\uffdd\012" +
    "\106\013\uffdd\014\uffdd\015\uffdd\016\uffdd\017\uffdd\020\uffdd" +
    "\021\uffdd\022\uffdd\023\uffdd\024\uffdd\025\uffdd\026\uffdd\027" +
    "\uffdd\030\uffdd\001\002\000\036\007\uffc8\013\uffc8\014\uffc8" +
    "\015\uffc8\016\uffc8\017\uffc8\020\uffc8\021\uffc8\022\uffc8\023" +
    "\uffc8\024\uffc8\025\uffc8\027\uffc8\030\uffc8\001\002\000\034" +
    "\002\ufff0\004\ufff0\005\ufff0\006\ufff0\010\ufff0\011\ufff0\027" +
    "\ufff0\031\ufff0\032\ufff0\033\ufff0\034\ufff0\035\ufff0\036\ufff0" +
    "\001\002\000\004\027\105\001\002\000\026\004\uffe7\005" +
    "\uffe7\006\uffe7\010\uffe7\011\uffe7\027\uffe7\032\uffe7\033\uffe7" +
    "\034\uffe7\036\uffe7\001\002\000\036\007\uffce\013\uffce\014" +
    "\uffce\015\uffce\016\uffce\017\uffce\020\uffce\021\uffce\022\uffce" +
    "\023\uffce\024\uffce\025\uffce\027\uffce\030\uffce\001\002\000" +
    "\032\007\uffda\013\uffda\014\075\015\071\020\101\021\072" +
    "\022\076\023\102\024\074\025\073\027\uffda\030\uffda\001" +
    "\002\000\036\007\uffd2\013\uffd2\014\uffd2\015\uffd2\016\064" +
    "\017\066\020\uffd2\021\uffd2\022\uffd2\023\uffd2\024\uffd2\025" +
    "\uffd2\027\uffd2\030\uffd2\001\002\000\012\007\uffde\013\uffde" +
    "\027\uffde\030\uffde\001\002\000\026\004\uffeb\005\uffeb\006" +
    "\uffeb\010\uffeb\011\uffeb\027\uffeb\032\uffeb\033\uffeb\034\uffeb" +
    "\036\uffeb\001\002\000\026\004\uffe9\005\uffe9\006\uffe9\010" +
    "\uffe9\011\uffe9\027\uffe9\032\uffe9\033\uffe9\034\uffe9\036\uffe9" +
    "\001\002\000\026\004\uffe8\005\uffe8\006\uffe8\010\uffe8\011" +
    "\uffe8\027\uffe8\032\uffe8\033\uffe8\034\uffe8\036\uffe8\001\002" +
    "\000\036\007\uffc9\013\uffc9\014\uffc9\015\uffc9\016\uffc9\017" +
    "\uffc9\020\uffc9\021\uffc9\022\uffc9\023\uffc9\024\uffc9\025\uffc9" +
    "\027\uffc9\030\uffc9\001\002\000\040\007\uffca\013\uffca\014" +
    "\uffca\015\uffca\016\uffca\017\uffca\020\uffca\021\uffca\022\uffca" +
    "\023\uffca\024\uffca\025\uffca\026\062\027\uffca\030\uffca\001" +
    "\002\000\010\004\044\005\045\006\043\001\002\000\012" +
    "\007\uffdf\013\uffdf\027\uffdf\030\uffdf\001\002\000\010\004" +
    "\uffcd\005\uffcd\006\uffcd\001\002\000\010\004\044\005\045" +
    "\006\043\001\002\000\010\004\uffcc\005\uffcc\006\uffcc\001" +
    "\002\000\036\007\uffca\013\uffca\014\uffca\015\uffca\016\uffca" +
    "\017\uffca\020\uffca\021\uffca\022\uffca\023\uffca\024\uffca\025" +
    "\uffca\027\uffca\030\uffca\001\002\000\036\007\uffcf\013\uffcf" +
    "\014\uffcf\015\uffcf\016\uffcf\017\uffcf\020\uffcf\021\uffcf\022" +
    "\uffcf\023\uffcf\024\uffcf\025\uffcf\027\uffcf\030\uffcf\001\002" +
    "\000\010\004\uffd0\005\uffd0\006\uffd0\001\002\000\010\004" +
    "\uffd9\005\uffd9\006\uffd9\001\002\000\010\004\uffd4\005\uffd4" +
    "\006\uffd4\001\002\000\010\004\uffd5\005\uffd5\006\uffd5\001" +
    "\002\000\010\004\uffd1\005\uffd1\006\uffd1\001\002\000\010" +
    "\004\uffd7\005\uffd7\006\uffd7\001\002\000\010\004\044\005" +
    "\045\006\043\001\002\000\010\004\044\005\045\006\043" +
    "\001\002\000\010\004\uffd8\005\uffd8\006\uffd8\001\002\000" +
    "\010\004\uffd6\005\uffd6\006\uffd6\001\002\000\016\007\uffdb" +
    "\013\uffdb\014\075\015\071\027\uffdb\030\uffdb\001\002\000" +
    "\036\007\uffd3\013\uffd3\014\uffd3\015\uffd3\016\064\017\066" +
    "\020\uffd3\021\uffd3\022\uffd3\023\uffd3\024\uffd3\025\uffd3\027" +
    "\uffd3\030\uffd3\001\002\000\026\004\uffe6\005\uffe6\006\uffe6" +
    "\010\uffe6\011\uffe6\027\uffe6\032\uffe6\033\uffe6\034\uffe6\036" +
    "\uffe6\001\002\000\010\004\044\005\045\006\043\001\002" +
    "\000\012\004\044\005\045\006\043\007\uffc5\001\002\000" +
    "\006\007\uffc6\030\114\001\002\000\006\007\uffc3\030\uffc3" +
    "\001\002\000\004\007\113\001\002\000\036\007\uffc7\013" +
    "\uffc7\014\uffc7\015\uffc7\016\uffc7\017\uffc7\020\uffc7\021\uffc7" +
    "\022\uffc7\023\uffc7\024\uffc7\025\uffc7\027\uffc7\030\uffc7\001" +
    "\002\000\010\004\044\005\045\006\043\001\002\000\006" +
    "\007\uffc4\030\uffc4\001\002\000\004\013\117\001\002\000" +
    "\040\007\uffdc\013\uffdc\014\uffdc\015\uffdc\016\uffdc\017\uffdc" +
    "\020\uffdc\021\uffdc\022\uffdc\023\uffdc\024\uffdc\025\uffdc\026" +
    "\uffdc\027\uffdc\030\uffdc\001\002\000\004\007\121\001\002" +
    "\000\036\007\uffcb\013\uffcb\014\uffcb\015\uffcb\016\uffcb\017" +
    "\uffcb\020\uffcb\021\uffcb\022\uffcb\023\uffcb\024\uffcb\025\uffcb" +
    "\027\uffcb\030\uffcb\001\002\000\010\004\044\005\045\006" +
    "\043\001\002\000\004\007\124\001\002\000\022\004\044" +
    "\005\045\006\043\010\026\027\035\033\042\034\040\036" +
    "\037\001\002\000\026\004\uffe4\005\uffe4\006\uffe4\010\uffe4" +
    "\011\uffe4\027\uffe4\032\126\033\uffe4\034\uffe4\036\uffe4\001" +
    "\002\000\022\004\044\005\045\006\043\010\026\027\035" +
    "\033\042\034\040\036\037\001\002\000\026\004\uffe3\005" +
    "\uffe3\006\uffe3\010\uffe3\011\uffe3\027\uffe3\032\uffe3\033\uffe3" +
    "\034\uffe3\036\uffe3\001\002\000\004\027\132\001\002\000" +
    "\026\004\uffe1\005\uffe1\006\uffe1\010\uffe1\011\uffe1\027\uffe1" +
    "\032\uffe1\033\uffe1\034\uffe1\036\uffe1\001\002\000\026\004" +
    "\uffe0\005\uffe0\006\uffe0\010\uffe0\011\uffe0\027\uffe0\032\uffe0" +
    "\033\uffe0\034\uffe0\036\uffe0\001\002\000\010\004\044\005" +
    "\045\006\043\001\002\000\004\007\135\001\002\000\022" +
    "\004\044\005\045\006\043\010\026\027\035\033\042\034" +
    "\040\036\037\001\002\000\026\004\uffe2\005\uffe2\006\uffe2" +
    "\010\uffe2\011\uffe2\027\uffe2\032\uffe2\033\uffe2\034\uffe2\036" +
    "\uffe2\001\002\000\010\007\ufff2\012\140\030\ufff2\001\002" +
    "\000\004\013\141\001\002\000\006\007\ufff1\030\ufff1\001" +
    "\002\000\006\031\013\035\010\001\002\000\006\007\ufff4" +
    "\030\ufff4\001\002\000\004\013\145\001\002\000\004\027" +
    "\146\001\002\000\032\002\ufffa\004\ufffa\005\ufffa\006\ufffa" +
    "\010\ufffa\011\ufffa\027\ufffa\031\ufffa\033\ufffa\034\ufffa\035" +
    "\ufffa\036\ufffa\001\002\000\010\002\uffff\031\uffff\035\uffff" +
    "\001\002\000\004\002\001\001\002" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\146\000\016\002\003\003\006\004\011\005\005\006" +
    "\004\007\010\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\012\004\146\005\005\006\004\007" +
    "\010\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\012\007\021\010\022\011\017" +
    "\012\023\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\004" +
    "\013\026\001\001\000\004\014\027\001\001\000\002\001" +
    "\001\000\010\005\031\007\032\015\030\001\001\000\034" +
    "\013\040\016\035\017\054\020\055\021\056\022\047\023" +
    "\046\024\060\025\053\027\051\031\052\033\050\034\057" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\020\023\127\024\060\025\053\027\051\031\052\033" +
    "\050\034\057\001\001\000\002\001\001\000\002\001\001" +
    "\000\020\023\117\024\060\025\053\027\051\031\052\033" +
    "\050\034\057\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\006\026\077\030\076\001\001\000\004" +
    "\032\064\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\020\023\062\024\060\025\053\027\051\031" +
    "\052\033\050\034\057\001\001\000\002\001\001\000\002" +
    "\001\001\000\010\024\066\033\067\034\057\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\012\024\066" +
    "\031\103\033\050\034\057\001\001\000\014\024\066\027" +
    "\102\031\052\033\050\034\057\001\001\000\002\001\001" +
    "\000\002\001\001\000\004\030\076\001\001\000\004\032" +
    "\064\001\001\000\002\001\001\000\020\023\115\024\060" +
    "\025\053\027\051\031\052\033\050\034\057\001\001\000" +
    "\024\023\110\024\060\025\053\027\051\031\052\033\050" +
    "\034\057\035\111\036\107\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\020" +
    "\023\114\024\060\025\053\027\051\031\052\033\050\034" +
    "\057\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\020\023" +
    "\122\024\060\025\053\027\051\031\052\033\050\034\057" +
    "\001\001\000\002\001\001\000\034\013\040\016\124\017" +
    "\054\020\055\021\056\022\047\023\046\024\060\025\053" +
    "\027\051\031\052\033\050\034\057\001\001\000\002\001" +
    "\001\000\034\013\040\016\126\017\054\020\055\021\056" +
    "\022\047\023\046\024\060\025\053\027\051\031\052\033" +
    "\050\034\057\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\020\023\133\024" +
    "\060\025\053\027\051\031\052\033\050\034\057\001\001" +
    "\000\002\001\001\000\034\013\040\016\135\017\054\020" +
    "\055\021\056\022\047\023\046\024\060\025\053\027\051" +
    "\031\052\033\050\034\057\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\006" +
    "\007\021\012\142\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$CMinusParser$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
    {
      action_obj = new CUP$CMinusParser$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$CMinusParser$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 0;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}



  public static void main(String[] args) throws Exception {
    java.io.Reader r =
      (args.length == 0 || "-".equals(args[0]))
        ? new java.io.InputStreamReader(System.in)
        : new java.io.FileReader(args[0]);
    CMinusLexerCup lx = new CMinusLexerCup(r); // lexer “para CUP”
    CMinusParser p = new CMinusParser(lx);
    System.out.println(p.parse().value);
  }


/** Cup generated class to encapsulate user supplied action code.*/
@SuppressWarnings({"rawtypes", "unchecked", "unused"})
class CUP$CMinusParser$actions {
  private final CMinusParser parser;

  /** Constructor */
  CUP$CMinusParser$actions(CMinusParser parser) {
    this.parser = parser;
  }

  /** Method 0 with the actual generated action code for actions 0 to 300. */
  public final java_cup.runtime.Symbol CUP$CMinusParser$do_action_part00000000(
    int                        CUP$CMinusParser$act_num,
    java_cup.runtime.lr_parser CUP$CMinusParser$parser,
    java.util.Stack            CUP$CMinusParser$stack,
    int                        CUP$CMinusParser$top)
    throws java.lang.Exception
    {
      /* Symbol object for return from actions */
      java_cup.runtime.Symbol CUP$CMinusParser$result;

      /* select the action based on the action number */
      switch (CUP$CMinusParser$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // $START ::= program EOF 
            {
              Object RESULT =null;
		int start_valleft = ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.elementAt(CUP$CMinusParser$top-1)).left;
		int start_valright = ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.elementAt(CUP$CMinusParser$top-1)).right;
		Object start_val = (Object)((java_cup.runtime.Symbol) CUP$CMinusParser$stack.elementAt(CUP$CMinusParser$top-1)).value;
		RESULT = start_val;
              CUP$CMinusParser$result = parser.getSymbolFactory().newSymbol("$START",0, ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.elementAt(CUP$CMinusParser$top-1)), ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.peek()), RESULT);
            }
          /* ACCEPT */
          CUP$CMinusParser$parser.done_parsing();
          return CUP$CMinusParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // program ::= declaration_list 
            {
              Object RESULT =null;
		int dlleft = ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.peek()).left;
		int dlright = ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.peek()).right;
		Object dl = (Object)((java_cup.runtime.Symbol) CUP$CMinusParser$stack.peek()).value;

              CUP$CMinusParser$result = parser.getSymbolFactory().newSymbol("program",0, ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.peek()), RESULT);
            }
          return CUP$CMinusParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 2: // declaration_list ::= declaration_list declaration 
            {
              Object RESULT =null;
		int dlleft = ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.elementAt(CUP$CMinusParser$top-1)).left;
		int dlright = ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.elementAt(CUP$CMinusParser$top-1)).right;
		Object dl = (Object)((java_cup.runtime.Symbol) CUP$CMinusParser$stack.elementAt(CUP$CMinusParser$top-1)).value;
		int dclleft = ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.peek()).left;
		int dclright = ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.peek()).right;
		Object dcl = (Object)((java_cup.runtime.Symbol) CUP$CMinusParser$stack.peek()).value;

              CUP$CMinusParser$result = parser.getSymbolFactory().newSymbol("declaration_list",1, ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.elementAt(CUP$CMinusParser$top-1)), ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.peek()), RESULT);
            }
          return CUP$CMinusParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 3: // declaration_list ::= declaration 
            {
              Object RESULT =null;
		int dclleft = ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.peek()).left;
		int dclright = ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.peek()).right;
		Object dcl = (Object)((java_cup.runtime.Symbol) CUP$CMinusParser$stack.peek()).value;

              CUP$CMinusParser$result = parser.getSymbolFactory().newSymbol("declaration_list",1, ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.peek()), RESULT);
            }
          return CUP$CMinusParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 4: // declaration ::= var_declaration 
            {
              Object RESULT =null;
		int vardleft = ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.peek()).left;
		int vardright = ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.peek()).right;
		Object vard = (Object)((java_cup.runtime.Symbol) CUP$CMinusParser$stack.peek()).value;

              CUP$CMinusParser$result = parser.getSymbolFactory().newSymbol("declaration",2, ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.peek()), RESULT);
            }
          return CUP$CMinusParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 5: // declaration ::= fun_declaration 
            {
              Object RESULT =null;
		int fundleft = ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.peek()).left;
		int fundright = ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.peek()).right;
		Object fund = (Object)((java_cup.runtime.Symbol) CUP$CMinusParser$stack.peek()).value;

              CUP$CMinusParser$result = parser.getSymbolFactory().newSymbol("declaration",2, ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.peek()), RESULT);
            }
          return CUP$CMinusParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 6: // var_declaration ::= type_specifier ID SEMICOLON 
            {
              Object RESULT =null;
		int typspcleft = ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.elementAt(CUP$CMinusParser$top-2)).left;
		int typspcright = ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.elementAt(CUP$CMinusParser$top-2)).right;
		Object typspc = (Object)((java_cup.runtime.Symbol) CUP$CMinusParser$stack.elementAt(CUP$CMinusParser$top-2)).value;

              CUP$CMinusParser$result = parser.getSymbolFactory().newSymbol("var_declaration",3, ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.elementAt(CUP$CMinusParser$top-2)), ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.peek()), RESULT);
            }
          return CUP$CMinusParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 7: // var_declaration ::= type_specifier ID LBRACK NUM RBRACK SEMICOLON 
            {
              Object RESULT =null;
		int typspcleft = ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.elementAt(CUP$CMinusParser$top-5)).left;
		int typspcright = ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.elementAt(CUP$CMinusParser$top-5)).right;
		Object typspc = (Object)((java_cup.runtime.Symbol) CUP$CMinusParser$stack.elementAt(CUP$CMinusParser$top-5)).value;

              CUP$CMinusParser$result = parser.getSymbolFactory().newSymbol("var_declaration",3, ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.elementAt(CUP$CMinusParser$top-5)), ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.peek()), RESULT);
            }
          return CUP$CMinusParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 8: // type_specifier ::= INT 
            {
              Object RESULT =null;

              CUP$CMinusParser$result = parser.getSymbolFactory().newSymbol("type_specifier",5, ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.peek()), RESULT);
            }
          return CUP$CMinusParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 9: // type_specifier ::= VOID 
            {
              Object RESULT =null;

              CUP$CMinusParser$result = parser.getSymbolFactory().newSymbol("type_specifier",5, ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.peek()), RESULT);
            }
          return CUP$CMinusParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 10: // fun_declaration ::= type_specifier ID LPAREN params RPAREN compound_stmt 
            {
              Object RESULT =null;
		int typspcleft = ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.elementAt(CUP$CMinusParser$top-5)).left;
		int typspcright = ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.elementAt(CUP$CMinusParser$top-5)).right;
		Object typspc = (Object)((java_cup.runtime.Symbol) CUP$CMinusParser$stack.elementAt(CUP$CMinusParser$top-5)).value;
		int csleft = ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.peek()).left;
		int csright = ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.peek()).right;
		Object cs = (Object)((java_cup.runtime.Symbol) CUP$CMinusParser$stack.peek()).value;

              CUP$CMinusParser$result = parser.getSymbolFactory().newSymbol("fun_declaration",4, ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.elementAt(CUP$CMinusParser$top-5)), ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.peek()), RESULT);
            }
          return CUP$CMinusParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 11: // params ::= param_list 
            {
              Object RESULT =null;
		int plleft = ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.peek()).left;
		int plright = ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.peek()).right;
		Object pl = (Object)((java_cup.runtime.Symbol) CUP$CMinusParser$stack.peek()).value;

              CUP$CMinusParser$result = parser.getSymbolFactory().newSymbol("params",6, ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.peek()), RESULT);
            }
          return CUP$CMinusParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 12: // params ::= VOID 
            {
              Object RESULT =null;

              CUP$CMinusParser$result = parser.getSymbolFactory().newSymbol("params",6, ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.peek()), RESULT);
            }
          return CUP$CMinusParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 13: // param_list ::= param_list COMMA param 
            {
              Object RESULT =null;
		int plleft = ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.elementAt(CUP$CMinusParser$top-2)).left;
		int plright = ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.elementAt(CUP$CMinusParser$top-2)).right;
		Object pl = (Object)((java_cup.runtime.Symbol) CUP$CMinusParser$stack.elementAt(CUP$CMinusParser$top-2)).value;
		int pleft = ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.peek()).left;
		int pright = ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.peek()).right;
		Object p = (Object)((java_cup.runtime.Symbol) CUP$CMinusParser$stack.peek()).value;

              CUP$CMinusParser$result = parser.getSymbolFactory().newSymbol("param_list",7, ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.elementAt(CUP$CMinusParser$top-2)), ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.peek()), RESULT);
            }
          return CUP$CMinusParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 14: // param_list ::= param 
            {
              Object RESULT =null;
		int pleft = ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.peek()).left;
		int pright = ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.peek()).right;
		Object p = (Object)((java_cup.runtime.Symbol) CUP$CMinusParser$stack.peek()).value;

              CUP$CMinusParser$result = parser.getSymbolFactory().newSymbol("param_list",7, ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.peek()), RESULT);
            }
          return CUP$CMinusParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 15: // param ::= type_specifier ID 
            {
              Object RESULT =null;
		int typspcleft = ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.elementAt(CUP$CMinusParser$top-1)).left;
		int typspcright = ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.elementAt(CUP$CMinusParser$top-1)).right;
		Object typspc = (Object)((java_cup.runtime.Symbol) CUP$CMinusParser$stack.elementAt(CUP$CMinusParser$top-1)).value;

              CUP$CMinusParser$result = parser.getSymbolFactory().newSymbol("param",8, ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.elementAt(CUP$CMinusParser$top-1)), ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.peek()), RESULT);
            }
          return CUP$CMinusParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 16: // param ::= type_specifier ID LBRACK RBRACK 
            {
              Object RESULT =null;
		int typspcleft = ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.elementAt(CUP$CMinusParser$top-3)).left;
		int typspcright = ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.elementAt(CUP$CMinusParser$top-3)).right;
		Object typspc = (Object)((java_cup.runtime.Symbol) CUP$CMinusParser$stack.elementAt(CUP$CMinusParser$top-3)).value;

              CUP$CMinusParser$result = parser.getSymbolFactory().newSymbol("param",8, ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.elementAt(CUP$CMinusParser$top-3)), ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.peek()), RESULT);
            }
          return CUP$CMinusParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 17: // compound_stmt ::= LBRAC local_declarations statement_list RBRAC 
            {
              Object RESULT =null;
		int ldleft = ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.elementAt(CUP$CMinusParser$top-2)).left;
		int ldright = ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.elementAt(CUP$CMinusParser$top-2)).right;
		Object ld = (Object)((java_cup.runtime.Symbol) CUP$CMinusParser$stack.elementAt(CUP$CMinusParser$top-2)).value;
		int slleft = ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.elementAt(CUP$CMinusParser$top-1)).left;
		int slright = ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.elementAt(CUP$CMinusParser$top-1)).right;
		Object sl = (Object)((java_cup.runtime.Symbol) CUP$CMinusParser$stack.elementAt(CUP$CMinusParser$top-1)).value;

              CUP$CMinusParser$result = parser.getSymbolFactory().newSymbol("compound_stmt",9, ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.elementAt(CUP$CMinusParser$top-3)), ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.peek()), RESULT);
            }
          return CUP$CMinusParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 18: // local_declarations ::= local_declarations var_declaration 
            {
              Object RESULT =null;
		int ldleft = ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.elementAt(CUP$CMinusParser$top-1)).left;
		int ldright = ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.elementAt(CUP$CMinusParser$top-1)).right;
		Object ld = (Object)((java_cup.runtime.Symbol) CUP$CMinusParser$stack.elementAt(CUP$CMinusParser$top-1)).value;
		int vdleft = ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.peek()).left;
		int vdright = ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.peek()).right;
		Object vd = (Object)((java_cup.runtime.Symbol) CUP$CMinusParser$stack.peek()).value;

              CUP$CMinusParser$result = parser.getSymbolFactory().newSymbol("local_declarations",10, ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.elementAt(CUP$CMinusParser$top-1)), ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.peek()), RESULT);
            }
          return CUP$CMinusParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 19: // local_declarations ::= 
            {
              Object RESULT =null;

              CUP$CMinusParser$result = parser.getSymbolFactory().newSymbol("local_declarations",10, ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.peek()), RESULT);
            }
          return CUP$CMinusParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 20: // statement_list ::= statement_list statement 
            {
              Object RESULT =null;
		int slleft = ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.elementAt(CUP$CMinusParser$top-1)).left;
		int slright = ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.elementAt(CUP$CMinusParser$top-1)).right;
		Object sl = (Object)((java_cup.runtime.Symbol) CUP$CMinusParser$stack.elementAt(CUP$CMinusParser$top-1)).value;
		int sleft = ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.peek()).left;
		int sright = ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.peek()).right;
		Object s = (Object)((java_cup.runtime.Symbol) CUP$CMinusParser$stack.peek()).value;

              CUP$CMinusParser$result = parser.getSymbolFactory().newSymbol("statement_list",11, ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.elementAt(CUP$CMinusParser$top-1)), ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.peek()), RESULT);
            }
          return CUP$CMinusParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 21: // statement_list ::= 
            {
              Object RESULT =null;

              CUP$CMinusParser$result = parser.getSymbolFactory().newSymbol("statement_list",11, ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.peek()), RESULT);
            }
          return CUP$CMinusParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 22: // statement ::= expression_stmt 
            {
              Object RESULT =null;

              CUP$CMinusParser$result = parser.getSymbolFactory().newSymbol("statement",12, ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.peek()), RESULT);
            }
          return CUP$CMinusParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 23: // statement ::= compound_stmt 
            {
              Object RESULT =null;

              CUP$CMinusParser$result = parser.getSymbolFactory().newSymbol("statement",12, ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.peek()), RESULT);
            }
          return CUP$CMinusParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 24: // statement ::= selection_stmt 
            {
              Object RESULT =null;

              CUP$CMinusParser$result = parser.getSymbolFactory().newSymbol("statement",12, ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.peek()), RESULT);
            }
          return CUP$CMinusParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 25: // statement ::= iteration_stmt 
            {
              Object RESULT =null;

              CUP$CMinusParser$result = parser.getSymbolFactory().newSymbol("statement",12, ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.peek()), RESULT);
            }
          return CUP$CMinusParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 26: // statement ::= return_stmt 
            {
              Object RESULT =null;

              CUP$CMinusParser$result = parser.getSymbolFactory().newSymbol("statement",12, ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.peek()), RESULT);
            }
          return CUP$CMinusParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 27: // expression_stmt ::= expression SEMICOLON 
            {
              Object RESULT =null;

              CUP$CMinusParser$result = parser.getSymbolFactory().newSymbol("expression_stmt",13, ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.elementAt(CUP$CMinusParser$top-1)), ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.peek()), RESULT);
            }
          return CUP$CMinusParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 28: // expression_stmt ::= SEMICOLON 
            {
              Object RESULT =null;

              CUP$CMinusParser$result = parser.getSymbolFactory().newSymbol("expression_stmt",13, ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.peek()), RESULT);
            }
          return CUP$CMinusParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 29: // selection_stmt ::= IF LPAREN expression RPAREN statement 
            {
              Object RESULT =null;

              CUP$CMinusParser$result = parser.getSymbolFactory().newSymbol("selection_stmt",14, ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.elementAt(CUP$CMinusParser$top-4)), ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.peek()), RESULT);
            }
          return CUP$CMinusParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 30: // selection_stmt ::= IF LPAREN expression RPAREN statement ELSE statement 
            {
              Object RESULT =null;

              CUP$CMinusParser$result = parser.getSymbolFactory().newSymbol("selection_stmt",14, ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.elementAt(CUP$CMinusParser$top-6)), ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.peek()), RESULT);
            }
          return CUP$CMinusParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 31: // iteration_stmt ::= WHILE LPAREN expression RPAREN statement 
            {
              Object RESULT =null;

              CUP$CMinusParser$result = parser.getSymbolFactory().newSymbol("iteration_stmt",15, ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.elementAt(CUP$CMinusParser$top-4)), ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.peek()), RESULT);
            }
          return CUP$CMinusParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 32: // return_stmt ::= RETURN SEMICOLON 
            {
              Object RESULT =null;

              CUP$CMinusParser$result = parser.getSymbolFactory().newSymbol("return_stmt",16, ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.elementAt(CUP$CMinusParser$top-1)), ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.peek()), RESULT);
            }
          return CUP$CMinusParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 33: // return_stmt ::= RETURN expression SEMICOLON 
            {
              Object RESULT =null;

              CUP$CMinusParser$result = parser.getSymbolFactory().newSymbol("return_stmt",16, ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.elementAt(CUP$CMinusParser$top-2)), ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.peek()), RESULT);
            }
          return CUP$CMinusParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 34: // expression ::= var ASSIGN expression 
            {
              Object RESULT =null;

              CUP$CMinusParser$result = parser.getSymbolFactory().newSymbol("expression",17, ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.elementAt(CUP$CMinusParser$top-2)), ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.peek()), RESULT);
            }
          return CUP$CMinusParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 35: // expression ::= simple_expression 
            {
              Object RESULT =null;

              CUP$CMinusParser$result = parser.getSymbolFactory().newSymbol("expression",17, ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.peek()), RESULT);
            }
          return CUP$CMinusParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 36: // var ::= ID 
            {
              Object RESULT =null;

              CUP$CMinusParser$result = parser.getSymbolFactory().newSymbol("var",18, ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.peek()), RESULT);
            }
          return CUP$CMinusParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 37: // var ::= ID LBRACK expression RBRACK 
            {
              Object RESULT =null;

              CUP$CMinusParser$result = parser.getSymbolFactory().newSymbol("var",18, ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.elementAt(CUP$CMinusParser$top-3)), ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.peek()), RESULT);
            }
          return CUP$CMinusParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 38: // simple_expression ::= additive_expression relop additive_expression 
            {
              Object RESULT =null;

              CUP$CMinusParser$result = parser.getSymbolFactory().newSymbol("simple_expression",19, ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.elementAt(CUP$CMinusParser$top-2)), ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.peek()), RESULT);
            }
          return CUP$CMinusParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 39: // simple_expression ::= additive_expression 
            {
              Object RESULT =null;

              CUP$CMinusParser$result = parser.getSymbolFactory().newSymbol("simple_expression",19, ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.peek()), RESULT);
            }
          return CUP$CMinusParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 40: // relop ::= LESSTHANEQ 
            {
              Object RESULT =null;

              CUP$CMinusParser$result = parser.getSymbolFactory().newSymbol("relop",20, ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.peek()), RESULT);
            }
          return CUP$CMinusParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 41: // relop ::= LESSTHAN 
            {
              Object RESULT =null;

              CUP$CMinusParser$result = parser.getSymbolFactory().newSymbol("relop",20, ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.peek()), RESULT);
            }
          return CUP$CMinusParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 42: // relop ::= GREATERTHAN 
            {
              Object RESULT =null;

              CUP$CMinusParser$result = parser.getSymbolFactory().newSymbol("relop",20, ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.peek()), RESULT);
            }
          return CUP$CMinusParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 43: // relop ::= GREATERTHANEQ 
            {
              Object RESULT =null;

              CUP$CMinusParser$result = parser.getSymbolFactory().newSymbol("relop",20, ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.peek()), RESULT);
            }
          return CUP$CMinusParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 44: // relop ::= EQUAL 
            {
              Object RESULT =null;

              CUP$CMinusParser$result = parser.getSymbolFactory().newSymbol("relop",20, ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.peek()), RESULT);
            }
          return CUP$CMinusParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 45: // relop ::= NOTEQUAL 
            {
              Object RESULT =null;

              CUP$CMinusParser$result = parser.getSymbolFactory().newSymbol("relop",20, ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.peek()), RESULT);
            }
          return CUP$CMinusParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 46: // additive_expression ::= additive_expression addop term 
            {
              Object RESULT =null;

              CUP$CMinusParser$result = parser.getSymbolFactory().newSymbol("additive_expression",21, ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.elementAt(CUP$CMinusParser$top-2)), ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.peek()), RESULT);
            }
          return CUP$CMinusParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 47: // additive_expression ::= term 
            {
              Object RESULT =null;

              CUP$CMinusParser$result = parser.getSymbolFactory().newSymbol("additive_expression",21, ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.peek()), RESULT);
            }
          return CUP$CMinusParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 48: // addop ::= PLUS 
            {
              Object RESULT =null;

              CUP$CMinusParser$result = parser.getSymbolFactory().newSymbol("addop",22, ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.peek()), RESULT);
            }
          return CUP$CMinusParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 49: // addop ::= MINUS 
            {
              Object RESULT =null;

              CUP$CMinusParser$result = parser.getSymbolFactory().newSymbol("addop",22, ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.peek()), RESULT);
            }
          return CUP$CMinusParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 50: // term ::= term mulop factor 
            {
              Object RESULT =null;

              CUP$CMinusParser$result = parser.getSymbolFactory().newSymbol("term",23, ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.elementAt(CUP$CMinusParser$top-2)), ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.peek()), RESULT);
            }
          return CUP$CMinusParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 51: // term ::= factor 
            {
              Object RESULT =null;

              CUP$CMinusParser$result = parser.getSymbolFactory().newSymbol("term",23, ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.peek()), RESULT);
            }
          return CUP$CMinusParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 52: // mulop ::= STAR 
            {
              Object RESULT =null;

              CUP$CMinusParser$result = parser.getSymbolFactory().newSymbol("mulop",24, ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.peek()), RESULT);
            }
          return CUP$CMinusParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 53: // mulop ::= SLASH 
            {
              Object RESULT =null;

              CUP$CMinusParser$result = parser.getSymbolFactory().newSymbol("mulop",24, ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.peek()), RESULT);
            }
          return CUP$CMinusParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 54: // factor ::= LPAREN expression RPAREN 
            {
              Object RESULT =null;

              CUP$CMinusParser$result = parser.getSymbolFactory().newSymbol("factor",25, ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.elementAt(CUP$CMinusParser$top-2)), ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.peek()), RESULT);
            }
          return CUP$CMinusParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 55: // factor ::= var 
            {
              Object RESULT =null;

              CUP$CMinusParser$result = parser.getSymbolFactory().newSymbol("factor",25, ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.peek()), RESULT);
            }
          return CUP$CMinusParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 56: // factor ::= call 
            {
              Object RESULT =null;

              CUP$CMinusParser$result = parser.getSymbolFactory().newSymbol("factor",25, ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.peek()), RESULT);
            }
          return CUP$CMinusParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 57: // factor ::= NUM 
            {
              Object RESULT =null;

              CUP$CMinusParser$result = parser.getSymbolFactory().newSymbol("factor",25, ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.peek()), RESULT);
            }
          return CUP$CMinusParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 58: // call ::= ID LPAREN args RPAREN 
            {
              Object RESULT =null;

              CUP$CMinusParser$result = parser.getSymbolFactory().newSymbol("call",26, ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.elementAt(CUP$CMinusParser$top-3)), ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.peek()), RESULT);
            }
          return CUP$CMinusParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 59: // args ::= arg_list 
            {
              Object RESULT =null;

              CUP$CMinusParser$result = parser.getSymbolFactory().newSymbol("args",27, ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.peek()), RESULT);
            }
          return CUP$CMinusParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 60: // args ::= 
            {
              Object RESULT =null;

              CUP$CMinusParser$result = parser.getSymbolFactory().newSymbol("args",27, ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.peek()), RESULT);
            }
          return CUP$CMinusParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 61: // arg_list ::= arg_list COMMA expression 
            {
              Object RESULT =null;

              CUP$CMinusParser$result = parser.getSymbolFactory().newSymbol("arg_list",28, ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.elementAt(CUP$CMinusParser$top-2)), ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.peek()), RESULT);
            }
          return CUP$CMinusParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 62: // arg_list ::= expression 
            {
              Object RESULT =null;

              CUP$CMinusParser$result = parser.getSymbolFactory().newSymbol("arg_list",28, ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.peek()), RESULT);
            }
          return CUP$CMinusParser$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number "+CUP$CMinusParser$act_num+"found in internal parse table");

        }
    } /* end of method */

  /** Method splitting the generated action code into several parts. */
  public final java_cup.runtime.Symbol CUP$CMinusParser$do_action(
    int                        CUP$CMinusParser$act_num,
    java_cup.runtime.lr_parser CUP$CMinusParser$parser,
    java.util.Stack            CUP$CMinusParser$stack,
    int                        CUP$CMinusParser$top)
    throws java.lang.Exception
    {
              return CUP$CMinusParser$do_action_part00000000(
                               CUP$CMinusParser$act_num,
                               CUP$CMinusParser$parser,
                               CUP$CMinusParser$stack,
                               CUP$CMinusParser$top);
    }
}

}
