
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20150326 (SVN rev 63)
//----------------------------------------------------

import java_cup.runtime.Symbol;
import java_cup.runtime.XMLElement;

/** CUP v0.11b 20150326 (SVN rev 63) generated parser.
  */
@SuppressWarnings({"rawtypes"})
public class CMinusParser extends java_cup.runtime.lr_parser {

 public final Class getSymbolContainer() {
    return Sym.class;
}

  /** Default constructor. */
  @Deprecated
  public CMinusParser() {super();}

  /** Constructor which sets the default scanner. */
  @Deprecated
  public CMinusParser(java_cup.runtime.Scanner s) {super(s);}

  /** Constructor which sets the default scanner. */
  public CMinusParser(java_cup.runtime.Scanner s, java_cup.runtime.SymbolFactory sf) {super(s,sf);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\077\000\002\002\004\000\002\002\003\000\002\003" +
    "\004\000\002\003\003\000\002\004\003\000\002\004\003" +
    "\000\002\005\005\000\002\005\010\000\002\007\003\000" +
    "\002\007\003\000\002\006\010\000\002\010\003\000\002" +
    "\010\003\000\002\011\005\000\002\011\003\000\002\012" +
    "\004\000\002\012\006\000\002\013\006\000\002\014\004" +
    "\000\002\014\002\000\002\015\004\000\002\015\002\000" +
    "\002\016\003\000\002\016\003\000\002\016\003\000\002" +
    "\016\003\000\002\016\003\000\002\017\004\000\002\017" +
    "\003\000\002\020\007\000\002\020\011\000\002\021\007" +
    "\000\002\022\004\000\002\022\005\000\002\023\005\000" +
    "\002\023\003\000\002\024\003\000\002\024\006\000\002" +
    "\025\005\000\002\025\003\000\002\026\003\000\002\026" +
    "\003\000\002\026\003\000\002\026\003\000\002\026\003" +
    "\000\002\026\003\000\002\027\005\000\002\027\003\000" +
    "\002\030\003\000\002\030\003\000\002\031\005\000\002" +
    "\031\003\000\002\032\003\000\002\032\003\000\002\033" +
    "\005\000\002\033\003\000\002\033\003\000\002\033\003" +
    "\000\002\034\006\000\002\035\003\000\002\035\002\000" +
    "\002\036\005\000\002\036\003" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\146\000\006\006\013\007\010\001\002\000\004\002" +
    "\150\001\002\000\010\002\ufffc\006\ufffc\007\ufffc\001\002" +
    "\000\010\002\ufffd\006\ufffd\007\ufffd\001\002\000\010\002" +
    "\000\006\013\007\010\001\002\000\004\004\ufff8\001\002" +
    "\000\004\004\014\001\002\000\010\002\ufffe\006\ufffe\007" +
    "\ufffe\001\002\000\004\004\ufff9\001\002\000\010\027\017" +
    "\033\016\035\015\001\002\000\032\002\ufffb\004\ufffb\005" +
    "\ufffb\006\ufffb\007\ufffb\010\ufffb\012\ufffb\013\ufffb\027\ufffb" +
    "\031\ufffb\032\ufffb\035\ufffb\001\002\000\004\005\144\001" +
    "\002\000\006\006\013\007\021\001\002\000\006\030\ufff6" +
    "\036\142\001\002\000\006\004\ufff8\030\ufff5\001\002\000" +
    "\004\004\137\001\002\000\004\030\025\001\002\000\006" +
    "\030\ufff3\036\ufff3\001\002\000\004\031\026\001\002\000" +
    "\030\004\uffee\005\uffee\006\uffee\007\uffee\010\uffee\012\uffee" +
    "\013\uffee\027\uffee\031\uffee\032\uffee\035\uffee\001\002\000" +
    "\010\002\ufff7\006\ufff7\007\ufff7\001\002\000\030\004\uffec" +
    "\005\uffec\006\013\007\010\010\uffec\012\uffec\013\uffec\027" +
    "\uffec\031\uffec\032\uffec\035\uffec\001\002\000\024\004\044" +
    "\005\045\010\042\012\037\013\040\027\043\031\026\032" +
    "\046\035\035\001\002\000\030\004\uffef\005\uffef\006\uffef" +
    "\007\uffef\010\uffef\012\uffef\013\uffef\027\uffef\031\uffef\032" +
    "\uffef\035\uffef\001\002\000\004\004\034\001\002\000\006" +
    "\033\016\035\015\001\002\000\026\004\uffe5\005\uffe5\010" +
    "\uffe5\011\uffe5\012\uffe5\013\uffe5\027\uffe5\031\uffe5\032\uffe5" +
    "\035\uffe5\001\002\000\024\004\uffed\005\uffed\010\uffed\012" +
    "\uffed\013\uffed\027\uffed\031\uffed\032\uffed\035\uffed\001\002" +
    "\000\004\027\133\001\002\000\012\004\044\005\045\027" +
    "\043\035\131\001\002\000\026\004\uffea\005\uffea\010\uffea" +
    "\011\uffea\012\uffea\013\uffea\027\uffea\031\uffea\032\uffea\035" +
    "\uffea\001\002\000\004\027\122\001\002\000\010\004\044" +
    "\005\045\027\043\001\002\000\044\014\uffdd\015\uffdd\016" +
    "\uffdd\017\uffdd\020\uffdd\021\uffdd\022\uffdd\023\uffdd\024\uffdd" +
    "\025\uffdd\026\uffdd\027\107\030\uffdd\033\106\034\uffdd\035" +
    "\uffdd\036\uffdd\001\002\000\036\014\uffc8\015\uffc8\016\uffc8" +
    "\017\uffc8\020\uffc8\021\uffc8\022\uffc8\023\uffc8\024\uffc8\025" +
    "\uffc8\030\uffc8\034\uffc8\035\uffc8\036\uffc8\001\002\000\034" +
    "\002\ufff0\004\ufff0\005\ufff0\006\ufff0\007\ufff0\010\ufff0\011" +
    "\ufff0\012\ufff0\013\ufff0\027\ufff0\031\ufff0\032\ufff0\035\ufff0" +
    "\001\002\000\004\035\105\001\002\000\026\004\uffe7\005" +
    "\uffe7\010\uffe7\011\uffe7\012\uffe7\013\uffe7\027\uffe7\031\uffe7" +
    "\032\uffe7\035\uffe7\001\002\000\036\014\uffce\015\uffce\016" +
    "\uffce\017\uffce\020\uffce\021\uffce\022\uffce\023\uffce\024\uffce" +
    "\025\uffce\030\uffce\034\uffce\035\uffce\036\uffce\001\002\000" +
    "\032\014\075\015\071\020\101\021\072\022\076\023\102" +
    "\024\074\025\073\030\uffda\034\uffda\035\uffda\036\uffda\001" +
    "\002\000\036\014\uffd2\015\uffd2\016\064\017\066\020\uffd2" +
    "\021\uffd2\022\uffd2\023\uffd2\024\uffd2\025\uffd2\030\uffd2\034" +
    "\uffd2\035\uffd2\036\uffd2\001\002\000\012\030\uffde\034\uffde" +
    "\035\uffde\036\uffde\001\002\000\026\004\uffeb\005\uffeb\010" +
    "\uffeb\011\uffeb\012\uffeb\013\uffeb\027\uffeb\031\uffeb\032\uffeb" +
    "\035\uffeb\001\002\000\026\004\uffe9\005\uffe9\010\uffe9\011" +
    "\uffe9\012\uffe9\013\uffe9\027\uffe9\031\uffe9\032\uffe9\035\uffe9" +
    "\001\002\000\026\004\uffe8\005\uffe8\010\uffe8\011\uffe8\012" +
    "\uffe8\013\uffe8\027\uffe8\031\uffe8\032\uffe8\035\uffe8\001\002" +
    "\000\036\014\uffc9\015\uffc9\016\uffc9\017\uffc9\020\uffc9\021" +
    "\uffc9\022\uffc9\023\uffc9\024\uffc9\025\uffc9\030\uffc9\034\uffc9" +
    "\035\uffc9\036\uffc9\001\002\000\040\014\uffca\015\uffca\016" +
    "\uffca\017\uffca\020\uffca\021\uffca\022\uffca\023\uffca\024\uffca" +
    "\025\uffca\026\062\030\uffca\034\uffca\035\uffca\036\uffca\001" +
    "\002\000\010\004\044\005\045\027\043\001\002\000\012" +
    "\030\uffdf\034\uffdf\035\uffdf\036\uffdf\001\002\000\010\004" +
    "\uffcd\005\uffcd\027\uffcd\001\002\000\010\004\044\005\045" +
    "\027\043\001\002\000\010\004\uffcc\005\uffcc\027\uffcc\001" +
    "\002\000\036\014\uffca\015\uffca\016\uffca\017\uffca\020\uffca" +
    "\021\uffca\022\uffca\023\uffca\024\uffca\025\uffca\030\uffca\034" +
    "\uffca\035\uffca\036\uffca\001\002\000\036\014\uffcf\015\uffcf" +
    "\016\uffcf\017\uffcf\020\uffcf\021\uffcf\022\uffcf\023\uffcf\024" +
    "\uffcf\025\uffcf\030\uffcf\034\uffcf\035\uffcf\036\uffcf\001\002" +
    "\000\010\004\uffd0\005\uffd0\027\uffd0\001\002\000\010\004" +
    "\uffd9\005\uffd9\027\uffd9\001\002\000\010\004\uffd4\005\uffd4" +
    "\027\uffd4\001\002\000\010\004\uffd5\005\uffd5\027\uffd5\001" +
    "\002\000\010\004\uffd1\005\uffd1\027\uffd1\001\002\000\010" +
    "\004\uffd7\005\uffd7\027\uffd7\001\002\000\010\004\044\005" +
    "\045\027\043\001\002\000\010\004\044\005\045\027\043" +
    "\001\002\000\010\004\uffd8\005\uffd8\027\uffd8\001\002\000" +
    "\010\004\uffd6\005\uffd6\027\uffd6\001\002\000\016\014\075" +
    "\015\071\030\uffdb\034\uffdb\035\uffdb\036\uffdb\001\002\000" +
    "\036\014\uffd3\015\uffd3\016\064\017\066\020\uffd3\021\uffd3" +
    "\022\uffd3\023\uffd3\024\uffd3\025\uffd3\030\uffd3\034\uffd3\035" +
    "\uffd3\036\uffd3\001\002\000\026\004\uffe6\005\uffe6\010\uffe6" +
    "\011\uffe6\012\uffe6\013\uffe6\027\uffe6\031\uffe6\032\uffe6\035" +
    "\uffe6\001\002\000\010\004\044\005\045\027\043\001\002" +
    "\000\012\004\044\005\045\027\043\030\uffc5\001\002\000" +
    "\006\030\uffc6\036\114\001\002\000\006\030\uffc3\036\uffc3" +
    "\001\002\000\004\030\113\001\002\000\036\014\uffc7\015" +
    "\uffc7\016\uffc7\017\uffc7\020\uffc7\021\uffc7\022\uffc7\023\uffc7" +
    "\024\uffc7\025\uffc7\030\uffc7\034\uffc7\035\uffc7\036\uffc7\001" +
    "\002\000\010\004\044\005\045\027\043\001\002\000\006" +
    "\030\uffc4\036\uffc4\001\002\000\004\034\117\001\002\000" +
    "\040\014\uffdc\015\uffdc\016\uffdc\017\uffdc\020\uffdc\021\uffdc" +
    "\022\uffdc\023\uffdc\024\uffdc\025\uffdc\026\uffdc\030\uffdc\034" +
    "\uffdc\035\uffdc\036\uffdc\001\002\000\004\030\121\001\002" +
    "\000\036\014\uffcb\015\uffcb\016\uffcb\017\uffcb\020\uffcb\021" +
    "\uffcb\022\uffcb\023\uffcb\024\uffcb\025\uffcb\030\uffcb\034\uffcb" +
    "\035\uffcb\036\uffcb\001\002\000\010\004\044\005\045\027" +
    "\043\001\002\000\004\030\124\001\002\000\022\004\044" +
    "\005\045\010\042\012\037\013\040\027\043\031\026\035" +
    "\035\001\002\000\026\004\uffe4\005\uffe4\010\uffe4\011\126" +
    "\012\uffe4\013\uffe4\027\uffe4\031\uffe4\032\uffe4\035\uffe4\001" +
    "\002\000\022\004\044\005\045\010\042\012\037\013\040" +
    "\027\043\031\026\035\035\001\002\000\026\004\uffe3\005" +
    "\uffe3\010\uffe3\011\uffe3\012\uffe3\013\uffe3\027\uffe3\031\uffe3" +
    "\032\uffe3\035\uffe3\001\002\000\004\035\132\001\002\000" +
    "\026\004\uffe1\005\uffe1\010\uffe1\011\uffe1\012\uffe1\013\uffe1" +
    "\027\uffe1\031\uffe1\032\uffe1\035\uffe1\001\002\000\026\004" +
    "\uffe0\005\uffe0\010\uffe0\011\uffe0\012\uffe0\013\uffe0\027\uffe0" +
    "\031\uffe0\032\uffe0\035\uffe0\001\002\000\010\004\044\005" +
    "\045\027\043\001\002\000\004\030\135\001\002\000\022" +
    "\004\044\005\045\010\042\012\037\013\040\027\043\031" +
    "\026\035\035\001\002\000\026\004\uffe2\005\uffe2\010\uffe2" +
    "\011\uffe2\012\uffe2\013\uffe2\027\uffe2\031\uffe2\032\uffe2\035" +
    "\uffe2\001\002\000\010\030\ufff2\033\140\036\ufff2\001\002" +
    "\000\004\034\141\001\002\000\006\030\ufff1\036\ufff1\001" +
    "\002\000\006\006\013\007\010\001\002\000\006\030\ufff4" +
    "\036\ufff4\001\002\000\004\034\145\001\002\000\004\035" +
    "\146\001\002\000\032\002\ufffa\004\ufffa\005\ufffa\006\ufffa" +
    "\007\ufffa\010\ufffa\012\ufffa\013\ufffa\027\ufffa\031\ufffa\032" +
    "\ufffa\035\ufffa\001\002\000\010\002\uffff\006\uffff\007\uffff" +
    "\001\002\000\004\002\001\001\002" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\146\000\016\002\003\003\006\004\011\005\005\006" +
    "\004\007\010\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\012\004\146\005\005\006\004\007" +
    "\010\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\012\007\021\010\022\011\017" +
    "\012\023\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\004" +
    "\013\026\001\001\000\004\014\027\001\001\000\002\001" +
    "\001\000\010\005\031\007\032\015\030\001\001\000\034" +
    "\013\040\016\035\017\054\020\055\021\056\022\047\023" +
    "\046\024\060\025\053\027\051\031\052\033\050\034\057" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\020\023\127\024\060\025\053\027\051\031\052\033" +
    "\050\034\057\001\001\000\002\001\001\000\002\001\001" +
    "\000\020\023\117\024\060\025\053\027\051\031\052\033" +
    "\050\034\057\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\006\026\077\030\076\001\001\000\004" +
    "\032\064\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\020\023\062\024\060\025\053\027\051\031" +
    "\052\033\050\034\057\001\001\000\002\001\001\000\002" +
    "\001\001\000\010\024\066\033\067\034\057\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\012\024\066" +
    "\031\103\033\050\034\057\001\001\000\014\024\066\027" +
    "\102\031\052\033\050\034\057\001\001\000\002\001\001" +
    "\000\002\001\001\000\004\030\076\001\001\000\004\032" +
    "\064\001\001\000\002\001\001\000\020\023\115\024\060" +
    "\025\053\027\051\031\052\033\050\034\057\001\001\000" +
    "\024\023\110\024\060\025\053\027\051\031\052\033\050" +
    "\034\057\035\111\036\107\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\020" +
    "\023\114\024\060\025\053\027\051\031\052\033\050\034" +
    "\057\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\020\023" +
    "\122\024\060\025\053\027\051\031\052\033\050\034\057" +
    "\001\001\000\002\001\001\000\034\013\040\016\124\017" +
    "\054\020\055\021\056\022\047\023\046\024\060\025\053" +
    "\027\051\031\052\033\050\034\057\001\001\000\002\001" +
    "\001\000\034\013\040\016\126\017\054\020\055\021\056" +
    "\022\047\023\046\024\060\025\053\027\051\031\052\033" +
    "\050\034\057\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\020\023\133\024" +
    "\060\025\053\027\051\031\052\033\050\034\057\001\001" +
    "\000\002\001\001\000\034\013\040\016\135\017\054\020" +
    "\055\021\056\022\047\023\046\024\060\025\053\027\051" +
    "\031\052\033\050\034\057\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\006" +
    "\007\021\012\142\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$CMinusParser$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
    {
      action_obj = new CUP$CMinusParser$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$CMinusParser$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 0;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}



  public static void main(String[] args) throws Exception {
    java.io.Reader r =
      (args.length == 0 || "-".equals(args[0]))
        ? new java.io.InputStreamReader(System.in)
        : new java.io.FileReader(args[0]);
    CMinusLexerCup lx = new CMinusLexerCup(r);
    CMinusParser p = new CMinusParser(lx);
    Symbol result = p.parse();
    if (result.value != null) {
      System.out.println("=== ÁRVORE SINTÁTICA ===\n");
      System.out.println(result.value);
    }
  }


/** Cup generated class to encapsulate user supplied action code.*/
@SuppressWarnings({"rawtypes", "unchecked", "unused"})
class CUP$CMinusParser$actions {
  private final CMinusParser parser;

  /** Constructor */
  CUP$CMinusParser$actions(CMinusParser parser) {
    this.parser = parser;
  }

  /** Method 0 with the actual generated action code for actions 0 to 300. */
  public final java_cup.runtime.Symbol CUP$CMinusParser$do_action_part00000000(
    int                        CUP$CMinusParser$act_num,
    java_cup.runtime.lr_parser CUP$CMinusParser$parser,
    java.util.Stack            CUP$CMinusParser$stack,
    int                        CUP$CMinusParser$top)
    throws java.lang.Exception
    {
      /* Symbol object for return from actions */
      java_cup.runtime.Symbol CUP$CMinusParser$result;

      /* select the action based on the action number */
      switch (CUP$CMinusParser$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // $START ::= program EOF 
            {
              Object RESULT =null;
		int start_valleft = ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.elementAt(CUP$CMinusParser$top-1)).left;
		int start_valright = ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.elementAt(CUP$CMinusParser$top-1)).right;
		ASTNode start_val = (ASTNode)((java_cup.runtime.Symbol) CUP$CMinusParser$stack.elementAt(CUP$CMinusParser$top-1)).value;
		RESULT = start_val;
              CUP$CMinusParser$result = parser.getSymbolFactory().newSymbol("$START",0, ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.elementAt(CUP$CMinusParser$top-1)), ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.peek()), RESULT);
            }
          /* ACCEPT */
          CUP$CMinusParser$parser.done_parsing();
          return CUP$CMinusParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // program ::= declaration_list 
            {
              ASTNode RESULT =null;
		int dlleft = ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.peek()).left;
		int dlright = ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.peek()).right;
		ASTNode dl = (ASTNode)((java_cup.runtime.Symbol) CUP$CMinusParser$stack.peek()).value;
		 RESULT = new ASTNode("PROGRAM").addChild(dl); 
              CUP$CMinusParser$result = parser.getSymbolFactory().newSymbol("program",0, ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.peek()), RESULT);
            }
          return CUP$CMinusParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 2: // declaration_list ::= declaration_list declaration 
            {
              ASTNode RESULT =null;
		int dlleft = ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.elementAt(CUP$CMinusParser$top-1)).left;
		int dlright = ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.elementAt(CUP$CMinusParser$top-1)).right;
		ASTNode dl = (ASTNode)((java_cup.runtime.Symbol) CUP$CMinusParser$stack.elementAt(CUP$CMinusParser$top-1)).value;
		int dleft = ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.peek()).left;
		int dright = ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.peek()).right;
		ASTNode d = (ASTNode)((java_cup.runtime.Symbol) CUP$CMinusParser$stack.peek()).value;
		 RESULT = dl.addChild(d); 
              CUP$CMinusParser$result = parser.getSymbolFactory().newSymbol("declaration_list",1, ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.elementAt(CUP$CMinusParser$top-1)), ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.peek()), RESULT);
            }
          return CUP$CMinusParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 3: // declaration_list ::= declaration 
            {
              ASTNode RESULT =null;
		int dleft = ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.peek()).left;
		int dright = ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.peek()).right;
		ASTNode d = (ASTNode)((java_cup.runtime.Symbol) CUP$CMinusParser$stack.peek()).value;
		 RESULT = new ASTNode("DECLARATION_LIST").addChild(d); 
              CUP$CMinusParser$result = parser.getSymbolFactory().newSymbol("declaration_list",1, ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.peek()), RESULT);
            }
          return CUP$CMinusParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 4: // declaration ::= var_declaration 
            {
              ASTNode RESULT =null;
		int vdleft = ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.peek()).left;
		int vdright = ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.peek()).right;
		ASTNode vd = (ASTNode)((java_cup.runtime.Symbol) CUP$CMinusParser$stack.peek()).value;
		 RESULT = vd; 
              CUP$CMinusParser$result = parser.getSymbolFactory().newSymbol("declaration",2, ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.peek()), RESULT);
            }
          return CUP$CMinusParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 5: // declaration ::= fun_declaration 
            {
              ASTNode RESULT =null;
		int fdleft = ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.peek()).left;
		int fdright = ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.peek()).right;
		ASTNode fd = (ASTNode)((java_cup.runtime.Symbol) CUP$CMinusParser$stack.peek()).value;
		 RESULT = fd; 
              CUP$CMinusParser$result = parser.getSymbolFactory().newSymbol("declaration",2, ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.peek()), RESULT);
            }
          return CUP$CMinusParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 6: // var_declaration ::= type_specifier ID SEMICOLON 
            {
              ASTNode RESULT =null;
		int tsleft = ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.elementAt(CUP$CMinusParser$top-2)).left;
		int tsright = ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.elementAt(CUP$CMinusParser$top-2)).right;
		ASTNode ts = (ASTNode)((java_cup.runtime.Symbol) CUP$CMinusParser$stack.elementAt(CUP$CMinusParser$top-2)).value;
		int idleft = ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.elementAt(CUP$CMinusParser$top-1)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.elementAt(CUP$CMinusParser$top-1)).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$CMinusParser$stack.elementAt(CUP$CMinusParser$top-1)).value;
		 RESULT = new ASTNode("VAR_DECL").addChildren(ts, new ASTNode("ID", id)); 
              CUP$CMinusParser$result = parser.getSymbolFactory().newSymbol("var_declaration",3, ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.elementAt(CUP$CMinusParser$top-2)), ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.peek()), RESULT);
            }
          return CUP$CMinusParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 7: // var_declaration ::= type_specifier ID LBRACK NUM RBRACK SEMICOLON 
            {
              ASTNode RESULT =null;
		int tsleft = ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.elementAt(CUP$CMinusParser$top-5)).left;
		int tsright = ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.elementAt(CUP$CMinusParser$top-5)).right;
		ASTNode ts = (ASTNode)((java_cup.runtime.Symbol) CUP$CMinusParser$stack.elementAt(CUP$CMinusParser$top-5)).value;
		int idleft = ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.elementAt(CUP$CMinusParser$top-4)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.elementAt(CUP$CMinusParser$top-4)).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$CMinusParser$stack.elementAt(CUP$CMinusParser$top-4)).value;
		int nleft = ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.elementAt(CUP$CMinusParser$top-2)).left;
		int nright = ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.elementAt(CUP$CMinusParser$top-2)).right;
		String n = (String)((java_cup.runtime.Symbol) CUP$CMinusParser$stack.elementAt(CUP$CMinusParser$top-2)).value;
		 RESULT = new ASTNode("ARRAY_DECL").addChildren(ts, new ASTNode("ID", id), new ASTNode("SIZE", n)); 
              CUP$CMinusParser$result = parser.getSymbolFactory().newSymbol("var_declaration",3, ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.elementAt(CUP$CMinusParser$top-5)), ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.peek()), RESULT);
            }
          return CUP$CMinusParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 8: // type_specifier ::= INT 
            {
              ASTNode RESULT =null;
		int ileft = ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.peek()).left;
		int iright = ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.peek()).right;
		String i = (String)((java_cup.runtime.Symbol) CUP$CMinusParser$stack.peek()).value;
		 RESULT = new ASTNode("TYPE", "INT"); 
              CUP$CMinusParser$result = parser.getSymbolFactory().newSymbol("type_specifier",5, ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.peek()), RESULT);
            }
          return CUP$CMinusParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 9: // type_specifier ::= VOID 
            {
              ASTNode RESULT =null;
		int vleft = ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.peek()).left;
		int vright = ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.peek()).right;
		String v = (String)((java_cup.runtime.Symbol) CUP$CMinusParser$stack.peek()).value;
		 RESULT = new ASTNode("TYPE", "VOID"); 
              CUP$CMinusParser$result = parser.getSymbolFactory().newSymbol("type_specifier",5, ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.peek()), RESULT);
            }
          return CUP$CMinusParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 10: // fun_declaration ::= type_specifier ID LPAREN params RPAREN compound_stmt 
            {
              ASTNode RESULT =null;
		int tsleft = ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.elementAt(CUP$CMinusParser$top-5)).left;
		int tsright = ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.elementAt(CUP$CMinusParser$top-5)).right;
		ASTNode ts = (ASTNode)((java_cup.runtime.Symbol) CUP$CMinusParser$stack.elementAt(CUP$CMinusParser$top-5)).value;
		int idleft = ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.elementAt(CUP$CMinusParser$top-4)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.elementAt(CUP$CMinusParser$top-4)).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$CMinusParser$stack.elementAt(CUP$CMinusParser$top-4)).value;
		int pleft = ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.elementAt(CUP$CMinusParser$top-2)).left;
		int pright = ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.elementAt(CUP$CMinusParser$top-2)).right;
		ASTNode p = (ASTNode)((java_cup.runtime.Symbol) CUP$CMinusParser$stack.elementAt(CUP$CMinusParser$top-2)).value;
		int csleft = ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.peek()).left;
		int csright = ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.peek()).right;
		ASTNode cs = (ASTNode)((java_cup.runtime.Symbol) CUP$CMinusParser$stack.peek()).value;
		 RESULT = new ASTNode("FUN_DECL").addChildren(ts, new ASTNode("ID", id), p, cs); 
              CUP$CMinusParser$result = parser.getSymbolFactory().newSymbol("fun_declaration",4, ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.elementAt(CUP$CMinusParser$top-5)), ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.peek()), RESULT);
            }
          return CUP$CMinusParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 11: // params ::= param_list 
            {
              ASTNode RESULT =null;
		int plleft = ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.peek()).left;
		int plright = ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.peek()).right;
		ASTNode pl = (ASTNode)((java_cup.runtime.Symbol) CUP$CMinusParser$stack.peek()).value;
		 RESULT = new ASTNode("PARAMS").addChild(pl); 
              CUP$CMinusParser$result = parser.getSymbolFactory().newSymbol("params",6, ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.peek()), RESULT);
            }
          return CUP$CMinusParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 12: // params ::= VOID 
            {
              ASTNode RESULT =null;
		 RESULT = new ASTNode("PARAMS", "VOID"); 
              CUP$CMinusParser$result = parser.getSymbolFactory().newSymbol("params",6, ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.peek()), RESULT);
            }
          return CUP$CMinusParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 13: // param_list ::= param_list COMMA param 
            {
              ASTNode RESULT =null;
		int plleft = ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.elementAt(CUP$CMinusParser$top-2)).left;
		int plright = ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.elementAt(CUP$CMinusParser$top-2)).right;
		ASTNode pl = (ASTNode)((java_cup.runtime.Symbol) CUP$CMinusParser$stack.elementAt(CUP$CMinusParser$top-2)).value;
		int pleft = ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.peek()).left;
		int pright = ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.peek()).right;
		ASTNode p = (ASTNode)((java_cup.runtime.Symbol) CUP$CMinusParser$stack.peek()).value;
		 RESULT = pl.addChild(p); 
              CUP$CMinusParser$result = parser.getSymbolFactory().newSymbol("param_list",7, ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.elementAt(CUP$CMinusParser$top-2)), ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.peek()), RESULT);
            }
          return CUP$CMinusParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 14: // param_list ::= param 
            {
              ASTNode RESULT =null;
		int pleft = ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.peek()).left;
		int pright = ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.peek()).right;
		ASTNode p = (ASTNode)((java_cup.runtime.Symbol) CUP$CMinusParser$stack.peek()).value;
		 RESULT = new ASTNode("PARAM_LIST").addChild(p); 
              CUP$CMinusParser$result = parser.getSymbolFactory().newSymbol("param_list",7, ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.peek()), RESULT);
            }
          return CUP$CMinusParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 15: // param ::= type_specifier ID 
            {
              ASTNode RESULT =null;
		int tsleft = ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.elementAt(CUP$CMinusParser$top-1)).left;
		int tsright = ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.elementAt(CUP$CMinusParser$top-1)).right;
		ASTNode ts = (ASTNode)((java_cup.runtime.Symbol) CUP$CMinusParser$stack.elementAt(CUP$CMinusParser$top-1)).value;
		int idleft = ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.peek()).left;
		int idright = ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.peek()).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$CMinusParser$stack.peek()).value;
		 RESULT = new ASTNode("PARAM").addChildren(ts, new ASTNode("ID", id)); 
              CUP$CMinusParser$result = parser.getSymbolFactory().newSymbol("param",8, ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.elementAt(CUP$CMinusParser$top-1)), ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.peek()), RESULT);
            }
          return CUP$CMinusParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 16: // param ::= type_specifier ID LBRACK RBRACK 
            {
              ASTNode RESULT =null;
		int tsleft = ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.elementAt(CUP$CMinusParser$top-3)).left;
		int tsright = ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.elementAt(CUP$CMinusParser$top-3)).right;
		ASTNode ts = (ASTNode)((java_cup.runtime.Symbol) CUP$CMinusParser$stack.elementAt(CUP$CMinusParser$top-3)).value;
		int idleft = ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.elementAt(CUP$CMinusParser$top-2)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.elementAt(CUP$CMinusParser$top-2)).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$CMinusParser$stack.elementAt(CUP$CMinusParser$top-2)).value;
		 RESULT = new ASTNode("ARRAY_PARAM").addChildren(ts, new ASTNode("ID", id)); 
              CUP$CMinusParser$result = parser.getSymbolFactory().newSymbol("param",8, ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.elementAt(CUP$CMinusParser$top-3)), ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.peek()), RESULT);
            }
          return CUP$CMinusParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 17: // compound_stmt ::= LBRAC local_declarations statement_list RBRAC 
            {
              ASTNode RESULT =null;
		int ldleft = ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.elementAt(CUP$CMinusParser$top-2)).left;
		int ldright = ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.elementAt(CUP$CMinusParser$top-2)).right;
		ASTNode ld = (ASTNode)((java_cup.runtime.Symbol) CUP$CMinusParser$stack.elementAt(CUP$CMinusParser$top-2)).value;
		int slleft = ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.elementAt(CUP$CMinusParser$top-1)).left;
		int slright = ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.elementAt(CUP$CMinusParser$top-1)).right;
		ASTNode sl = (ASTNode)((java_cup.runtime.Symbol) CUP$CMinusParser$stack.elementAt(CUP$CMinusParser$top-1)).value;
		 RESULT = new ASTNode("COMPOUND_STMT").addChildren(ld, sl); 
              CUP$CMinusParser$result = parser.getSymbolFactory().newSymbol("compound_stmt",9, ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.elementAt(CUP$CMinusParser$top-3)), ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.peek()), RESULT);
            }
          return CUP$CMinusParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 18: // local_declarations ::= local_declarations var_declaration 
            {
              ASTNode RESULT =null;
		int ldleft = ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.elementAt(CUP$CMinusParser$top-1)).left;
		int ldright = ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.elementAt(CUP$CMinusParser$top-1)).right;
		ASTNode ld = (ASTNode)((java_cup.runtime.Symbol) CUP$CMinusParser$stack.elementAt(CUP$CMinusParser$top-1)).value;
		int vdleft = ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.peek()).left;
		int vdright = ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.peek()).right;
		ASTNode vd = (ASTNode)((java_cup.runtime.Symbol) CUP$CMinusParser$stack.peek()).value;
		 RESULT = ld.addChild(vd); 
              CUP$CMinusParser$result = parser.getSymbolFactory().newSymbol("local_declarations",10, ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.elementAt(CUP$CMinusParser$top-1)), ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.peek()), RESULT);
            }
          return CUP$CMinusParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 19: // local_declarations ::= 
            {
              ASTNode RESULT =null;
		 RESULT = new ASTNode("LOCAL_DECLS"); 
              CUP$CMinusParser$result = parser.getSymbolFactory().newSymbol("local_declarations",10, ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.peek()), RESULT);
            }
          return CUP$CMinusParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 20: // statement_list ::= statement_list statement 
            {
              ASTNode RESULT =null;
		int slleft = ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.elementAt(CUP$CMinusParser$top-1)).left;
		int slright = ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.elementAt(CUP$CMinusParser$top-1)).right;
		ASTNode sl = (ASTNode)((java_cup.runtime.Symbol) CUP$CMinusParser$stack.elementAt(CUP$CMinusParser$top-1)).value;
		int sleft = ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.peek()).left;
		int sright = ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.peek()).right;
		ASTNode s = (ASTNode)((java_cup.runtime.Symbol) CUP$CMinusParser$stack.peek()).value;
		 RESULT = sl.addChild(s); 
              CUP$CMinusParser$result = parser.getSymbolFactory().newSymbol("statement_list",11, ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.elementAt(CUP$CMinusParser$top-1)), ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.peek()), RESULT);
            }
          return CUP$CMinusParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 21: // statement_list ::= 
            {
              ASTNode RESULT =null;
		 RESULT = new ASTNode("STMT_LIST"); 
              CUP$CMinusParser$result = parser.getSymbolFactory().newSymbol("statement_list",11, ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.peek()), RESULT);
            }
          return CUP$CMinusParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 22: // statement ::= expression_stmt 
            {
              ASTNode RESULT =null;
		int sleft = ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.peek()).left;
		int sright = ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.peek()).right;
		ASTNode s = (ASTNode)((java_cup.runtime.Symbol) CUP$CMinusParser$stack.peek()).value;
		 RESULT = s; 
              CUP$CMinusParser$result = parser.getSymbolFactory().newSymbol("statement",12, ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.peek()), RESULT);
            }
          return CUP$CMinusParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 23: // statement ::= compound_stmt 
            {
              ASTNode RESULT =null;
		int sleft = ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.peek()).left;
		int sright = ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.peek()).right;
		ASTNode s = (ASTNode)((java_cup.runtime.Symbol) CUP$CMinusParser$stack.peek()).value;
		 RESULT = s; 
              CUP$CMinusParser$result = parser.getSymbolFactory().newSymbol("statement",12, ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.peek()), RESULT);
            }
          return CUP$CMinusParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 24: // statement ::= selection_stmt 
            {
              ASTNode RESULT =null;
		int sleft = ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.peek()).left;
		int sright = ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.peek()).right;
		ASTNode s = (ASTNode)((java_cup.runtime.Symbol) CUP$CMinusParser$stack.peek()).value;
		 RESULT = s; 
              CUP$CMinusParser$result = parser.getSymbolFactory().newSymbol("statement",12, ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.peek()), RESULT);
            }
          return CUP$CMinusParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 25: // statement ::= iteration_stmt 
            {
              ASTNode RESULT =null;
		int sleft = ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.peek()).left;
		int sright = ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.peek()).right;
		ASTNode s = (ASTNode)((java_cup.runtime.Symbol) CUP$CMinusParser$stack.peek()).value;
		 RESULT = s; 
              CUP$CMinusParser$result = parser.getSymbolFactory().newSymbol("statement",12, ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.peek()), RESULT);
            }
          return CUP$CMinusParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 26: // statement ::= return_stmt 
            {
              ASTNode RESULT =null;
		int sleft = ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.peek()).left;
		int sright = ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.peek()).right;
		ASTNode s = (ASTNode)((java_cup.runtime.Symbol) CUP$CMinusParser$stack.peek()).value;
		 RESULT = s; 
              CUP$CMinusParser$result = parser.getSymbolFactory().newSymbol("statement",12, ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.peek()), RESULT);
            }
          return CUP$CMinusParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 27: // expression_stmt ::= expression SEMICOLON 
            {
              ASTNode RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.elementAt(CUP$CMinusParser$top-1)).left;
		int eright = ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.elementAt(CUP$CMinusParser$top-1)).right;
		ASTNode e = (ASTNode)((java_cup.runtime.Symbol) CUP$CMinusParser$stack.elementAt(CUP$CMinusParser$top-1)).value;
		 RESULT = new ASTNode("EXPR_STMT").addChild(e); 
              CUP$CMinusParser$result = parser.getSymbolFactory().newSymbol("expression_stmt",13, ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.elementAt(CUP$CMinusParser$top-1)), ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.peek()), RESULT);
            }
          return CUP$CMinusParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 28: // expression_stmt ::= SEMICOLON 
            {
              ASTNode RESULT =null;
		 RESULT = new ASTNode("EMPTY_STMT"); 
              CUP$CMinusParser$result = parser.getSymbolFactory().newSymbol("expression_stmt",13, ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.peek()), RESULT);
            }
          return CUP$CMinusParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 29: // selection_stmt ::= IF LPAREN expression RPAREN statement 
            {
              ASTNode RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.elementAt(CUP$CMinusParser$top-2)).left;
		int eright = ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.elementAt(CUP$CMinusParser$top-2)).right;
		ASTNode e = (ASTNode)((java_cup.runtime.Symbol) CUP$CMinusParser$stack.elementAt(CUP$CMinusParser$top-2)).value;
		int sleft = ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.peek()).left;
		int sright = ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.peek()).right;
		ASTNode s = (ASTNode)((java_cup.runtime.Symbol) CUP$CMinusParser$stack.peek()).value;
		 RESULT = new ASTNode("IF").addChildren(e, s); 
              CUP$CMinusParser$result = parser.getSymbolFactory().newSymbol("selection_stmt",14, ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.elementAt(CUP$CMinusParser$top-4)), ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.peek()), RESULT);
            }
          return CUP$CMinusParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 30: // selection_stmt ::= IF LPAREN expression RPAREN statement ELSE statement 
            {
              ASTNode RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.elementAt(CUP$CMinusParser$top-4)).left;
		int eright = ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.elementAt(CUP$CMinusParser$top-4)).right;
		ASTNode e = (ASTNode)((java_cup.runtime.Symbol) CUP$CMinusParser$stack.elementAt(CUP$CMinusParser$top-4)).value;
		int s1left = ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.elementAt(CUP$CMinusParser$top-2)).left;
		int s1right = ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.elementAt(CUP$CMinusParser$top-2)).right;
		ASTNode s1 = (ASTNode)((java_cup.runtime.Symbol) CUP$CMinusParser$stack.elementAt(CUP$CMinusParser$top-2)).value;
		int s2left = ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.peek()).left;
		int s2right = ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.peek()).right;
		ASTNode s2 = (ASTNode)((java_cup.runtime.Symbol) CUP$CMinusParser$stack.peek()).value;
		 RESULT = new ASTNode("IF_ELSE").addChildren(e, s1, s2); 
              CUP$CMinusParser$result = parser.getSymbolFactory().newSymbol("selection_stmt",14, ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.elementAt(CUP$CMinusParser$top-6)), ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.peek()), RESULT);
            }
          return CUP$CMinusParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 31: // iteration_stmt ::= WHILE LPAREN expression RPAREN statement 
            {
              ASTNode RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.elementAt(CUP$CMinusParser$top-2)).left;
		int eright = ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.elementAt(CUP$CMinusParser$top-2)).right;
		ASTNode e = (ASTNode)((java_cup.runtime.Symbol) CUP$CMinusParser$stack.elementAt(CUP$CMinusParser$top-2)).value;
		int sleft = ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.peek()).left;
		int sright = ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.peek()).right;
		ASTNode s = (ASTNode)((java_cup.runtime.Symbol) CUP$CMinusParser$stack.peek()).value;
		 RESULT = new ASTNode("WHILE").addChildren(e, s); 
              CUP$CMinusParser$result = parser.getSymbolFactory().newSymbol("iteration_stmt",15, ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.elementAt(CUP$CMinusParser$top-4)), ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.peek()), RESULT);
            }
          return CUP$CMinusParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 32: // return_stmt ::= RETURN SEMICOLON 
            {
              ASTNode RESULT =null;
		 RESULT = new ASTNode("RETURN"); 
              CUP$CMinusParser$result = parser.getSymbolFactory().newSymbol("return_stmt",16, ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.elementAt(CUP$CMinusParser$top-1)), ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.peek()), RESULT);
            }
          return CUP$CMinusParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 33: // return_stmt ::= RETURN expression SEMICOLON 
            {
              ASTNode RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.elementAt(CUP$CMinusParser$top-1)).left;
		int eright = ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.elementAt(CUP$CMinusParser$top-1)).right;
		ASTNode e = (ASTNode)((java_cup.runtime.Symbol) CUP$CMinusParser$stack.elementAt(CUP$CMinusParser$top-1)).value;
		 RESULT = new ASTNode("RETURN").addChild(e); 
              CUP$CMinusParser$result = parser.getSymbolFactory().newSymbol("return_stmt",16, ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.elementAt(CUP$CMinusParser$top-2)), ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.peek()), RESULT);
            }
          return CUP$CMinusParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 34: // expression ::= var ASSIGN expression 
            {
              ASTNode RESULT =null;
		int vleft = ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.elementAt(CUP$CMinusParser$top-2)).left;
		int vright = ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.elementAt(CUP$CMinusParser$top-2)).right;
		ASTNode v = (ASTNode)((java_cup.runtime.Symbol) CUP$CMinusParser$stack.elementAt(CUP$CMinusParser$top-2)).value;
		int eleft = ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.peek()).right;
		ASTNode e = (ASTNode)((java_cup.runtime.Symbol) CUP$CMinusParser$stack.peek()).value;
		 RESULT = new ASTNode("ASSIGN").addChildren(v, e); 
              CUP$CMinusParser$result = parser.getSymbolFactory().newSymbol("expression",17, ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.elementAt(CUP$CMinusParser$top-2)), ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.peek()), RESULT);
            }
          return CUP$CMinusParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 35: // expression ::= simple_expression 
            {
              ASTNode RESULT =null;
		int seleft = ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.peek()).left;
		int seright = ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.peek()).right;
		ASTNode se = (ASTNode)((java_cup.runtime.Symbol) CUP$CMinusParser$stack.peek()).value;
		 RESULT = se; 
              CUP$CMinusParser$result = parser.getSymbolFactory().newSymbol("expression",17, ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.peek()), RESULT);
            }
          return CUP$CMinusParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 36: // var ::= ID 
            {
              ASTNode RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.peek()).left;
		int idright = ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.peek()).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$CMinusParser$stack.peek()).value;
		 RESULT = new ASTNode("VAR", id); 
              CUP$CMinusParser$result = parser.getSymbolFactory().newSymbol("var",18, ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.peek()), RESULT);
            }
          return CUP$CMinusParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 37: // var ::= ID LBRACK expression RBRACK 
            {
              ASTNode RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.elementAt(CUP$CMinusParser$top-3)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.elementAt(CUP$CMinusParser$top-3)).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$CMinusParser$stack.elementAt(CUP$CMinusParser$top-3)).value;
		int eleft = ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.elementAt(CUP$CMinusParser$top-1)).left;
		int eright = ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.elementAt(CUP$CMinusParser$top-1)).right;
		ASTNode e = (ASTNode)((java_cup.runtime.Symbol) CUP$CMinusParser$stack.elementAt(CUP$CMinusParser$top-1)).value;
		 RESULT = new ASTNode("ARRAY_ACCESS", id).addChild(e); 
              CUP$CMinusParser$result = parser.getSymbolFactory().newSymbol("var",18, ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.elementAt(CUP$CMinusParser$top-3)), ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.peek()), RESULT);
            }
          return CUP$CMinusParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 38: // simple_expression ::= additive_expression relop additive_expression 
            {
              ASTNode RESULT =null;
		int ae1left = ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.elementAt(CUP$CMinusParser$top-2)).left;
		int ae1right = ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.elementAt(CUP$CMinusParser$top-2)).right;
		ASTNode ae1 = (ASTNode)((java_cup.runtime.Symbol) CUP$CMinusParser$stack.elementAt(CUP$CMinusParser$top-2)).value;
		int opleft = ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.elementAt(CUP$CMinusParser$top-1)).left;
		int opright = ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.elementAt(CUP$CMinusParser$top-1)).right;
		ASTNode op = (ASTNode)((java_cup.runtime.Symbol) CUP$CMinusParser$stack.elementAt(CUP$CMinusParser$top-1)).value;
		int ae2left = ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.peek()).left;
		int ae2right = ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.peek()).right;
		ASTNode ae2 = (ASTNode)((java_cup.runtime.Symbol) CUP$CMinusParser$stack.peek()).value;
		 RESULT = op.addChildren(ae1, ae2); 
              CUP$CMinusParser$result = parser.getSymbolFactory().newSymbol("simple_expression",19, ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.elementAt(CUP$CMinusParser$top-2)), ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.peek()), RESULT);
            }
          return CUP$CMinusParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 39: // simple_expression ::= additive_expression 
            {
              ASTNode RESULT =null;
		int aeleft = ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.peek()).left;
		int aeright = ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.peek()).right;
		ASTNode ae = (ASTNode)((java_cup.runtime.Symbol) CUP$CMinusParser$stack.peek()).value;
		 RESULT = ae; 
              CUP$CMinusParser$result = parser.getSymbolFactory().newSymbol("simple_expression",19, ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.peek()), RESULT);
            }
          return CUP$CMinusParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 40: // relop ::= LESSTHANEQ 
            {
              ASTNode RESULT =null;
		int opleft = ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.peek()).left;
		int opright = ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.peek()).right;
		String op = (String)((java_cup.runtime.Symbol) CUP$CMinusParser$stack.peek()).value;
		 RESULT = new ASTNode("OP", op); 
              CUP$CMinusParser$result = parser.getSymbolFactory().newSymbol("relop",20, ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.peek()), RESULT);
            }
          return CUP$CMinusParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 41: // relop ::= LESSTHAN 
            {
              ASTNode RESULT =null;
		int opleft = ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.peek()).left;
		int opright = ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.peek()).right;
		String op = (String)((java_cup.runtime.Symbol) CUP$CMinusParser$stack.peek()).value;
		 RESULT = new ASTNode("OP", op); 
              CUP$CMinusParser$result = parser.getSymbolFactory().newSymbol("relop",20, ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.peek()), RESULT);
            }
          return CUP$CMinusParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 42: // relop ::= GREATERTHAN 
            {
              ASTNode RESULT =null;
		int opleft = ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.peek()).left;
		int opright = ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.peek()).right;
		String op = (String)((java_cup.runtime.Symbol) CUP$CMinusParser$stack.peek()).value;
		 RESULT = new ASTNode("OP", op); 
              CUP$CMinusParser$result = parser.getSymbolFactory().newSymbol("relop",20, ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.peek()), RESULT);
            }
          return CUP$CMinusParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 43: // relop ::= GREATERTHANEQ 
            {
              ASTNode RESULT =null;
		int opleft = ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.peek()).left;
		int opright = ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.peek()).right;
		String op = (String)((java_cup.runtime.Symbol) CUP$CMinusParser$stack.peek()).value;
		 RESULT = new ASTNode("OP", op); 
              CUP$CMinusParser$result = parser.getSymbolFactory().newSymbol("relop",20, ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.peek()), RESULT);
            }
          return CUP$CMinusParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 44: // relop ::= EQUAL 
            {
              ASTNode RESULT =null;
		int opleft = ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.peek()).left;
		int opright = ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.peek()).right;
		String op = (String)((java_cup.runtime.Symbol) CUP$CMinusParser$stack.peek()).value;
		 RESULT = new ASTNode("OP", op); 
              CUP$CMinusParser$result = parser.getSymbolFactory().newSymbol("relop",20, ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.peek()), RESULT);
            }
          return CUP$CMinusParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 45: // relop ::= NOTEQUAL 
            {
              ASTNode RESULT =null;
		int opleft = ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.peek()).left;
		int opright = ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.peek()).right;
		String op = (String)((java_cup.runtime.Symbol) CUP$CMinusParser$stack.peek()).value;
		 RESULT = new ASTNode("OP", op); 
              CUP$CMinusParser$result = parser.getSymbolFactory().newSymbol("relop",20, ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.peek()), RESULT);
            }
          return CUP$CMinusParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 46: // additive_expression ::= additive_expression addop term 
            {
              ASTNode RESULT =null;
		int aeleft = ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.elementAt(CUP$CMinusParser$top-2)).left;
		int aeright = ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.elementAt(CUP$CMinusParser$top-2)).right;
		ASTNode ae = (ASTNode)((java_cup.runtime.Symbol) CUP$CMinusParser$stack.elementAt(CUP$CMinusParser$top-2)).value;
		int opleft = ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.elementAt(CUP$CMinusParser$top-1)).left;
		int opright = ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.elementAt(CUP$CMinusParser$top-1)).right;
		ASTNode op = (ASTNode)((java_cup.runtime.Symbol) CUP$CMinusParser$stack.elementAt(CUP$CMinusParser$top-1)).value;
		int tleft = ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.peek()).left;
		int tright = ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.peek()).right;
		ASTNode t = (ASTNode)((java_cup.runtime.Symbol) CUP$CMinusParser$stack.peek()).value;
		 RESULT = op.addChildren(ae, t); 
              CUP$CMinusParser$result = parser.getSymbolFactory().newSymbol("additive_expression",21, ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.elementAt(CUP$CMinusParser$top-2)), ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.peek()), RESULT);
            }
          return CUP$CMinusParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 47: // additive_expression ::= term 
            {
              ASTNode RESULT =null;
		int tleft = ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.peek()).left;
		int tright = ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.peek()).right;
		ASTNode t = (ASTNode)((java_cup.runtime.Symbol) CUP$CMinusParser$stack.peek()).value;
		 RESULT = t; 
              CUP$CMinusParser$result = parser.getSymbolFactory().newSymbol("additive_expression",21, ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.peek()), RESULT);
            }
          return CUP$CMinusParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 48: // addop ::= PLUS 
            {
              ASTNode RESULT =null;
		int opleft = ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.peek()).left;
		int opright = ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.peek()).right;
		String op = (String)((java_cup.runtime.Symbol) CUP$CMinusParser$stack.peek()).value;
		 RESULT = new ASTNode("OP", op); 
              CUP$CMinusParser$result = parser.getSymbolFactory().newSymbol("addop",22, ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.peek()), RESULT);
            }
          return CUP$CMinusParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 49: // addop ::= MINUS 
            {
              ASTNode RESULT =null;
		int opleft = ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.peek()).left;
		int opright = ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.peek()).right;
		String op = (String)((java_cup.runtime.Symbol) CUP$CMinusParser$stack.peek()).value;
		 RESULT = new ASTNode("OP", op); 
              CUP$CMinusParser$result = parser.getSymbolFactory().newSymbol("addop",22, ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.peek()), RESULT);
            }
          return CUP$CMinusParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 50: // term ::= term mulop factor 
            {
              ASTNode RESULT =null;
		int tleft = ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.elementAt(CUP$CMinusParser$top-2)).left;
		int tright = ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.elementAt(CUP$CMinusParser$top-2)).right;
		ASTNode t = (ASTNode)((java_cup.runtime.Symbol) CUP$CMinusParser$stack.elementAt(CUP$CMinusParser$top-2)).value;
		int opleft = ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.elementAt(CUP$CMinusParser$top-1)).left;
		int opright = ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.elementAt(CUP$CMinusParser$top-1)).right;
		ASTNode op = (ASTNode)((java_cup.runtime.Symbol) CUP$CMinusParser$stack.elementAt(CUP$CMinusParser$top-1)).value;
		int fleft = ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.peek()).left;
		int fright = ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.peek()).right;
		ASTNode f = (ASTNode)((java_cup.runtime.Symbol) CUP$CMinusParser$stack.peek()).value;
		 RESULT = op.addChildren(t, f); 
              CUP$CMinusParser$result = parser.getSymbolFactory().newSymbol("term",23, ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.elementAt(CUP$CMinusParser$top-2)), ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.peek()), RESULT);
            }
          return CUP$CMinusParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 51: // term ::= factor 
            {
              ASTNode RESULT =null;
		int fleft = ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.peek()).left;
		int fright = ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.peek()).right;
		ASTNode f = (ASTNode)((java_cup.runtime.Symbol) CUP$CMinusParser$stack.peek()).value;
		 RESULT = f; 
              CUP$CMinusParser$result = parser.getSymbolFactory().newSymbol("term",23, ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.peek()), RESULT);
            }
          return CUP$CMinusParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 52: // mulop ::= STAR 
            {
              ASTNode RESULT =null;
		int opleft = ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.peek()).left;
		int opright = ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.peek()).right;
		String op = (String)((java_cup.runtime.Symbol) CUP$CMinusParser$stack.peek()).value;
		 RESULT = new ASTNode("OP", op); 
              CUP$CMinusParser$result = parser.getSymbolFactory().newSymbol("mulop",24, ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.peek()), RESULT);
            }
          return CUP$CMinusParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 53: // mulop ::= SLASH 
            {
              ASTNode RESULT =null;
		int opleft = ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.peek()).left;
		int opright = ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.peek()).right;
		String op = (String)((java_cup.runtime.Symbol) CUP$CMinusParser$stack.peek()).value;
		 RESULT = new ASTNode("OP", op); 
              CUP$CMinusParser$result = parser.getSymbolFactory().newSymbol("mulop",24, ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.peek()), RESULT);
            }
          return CUP$CMinusParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 54: // factor ::= LPAREN expression RPAREN 
            {
              ASTNode RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.elementAt(CUP$CMinusParser$top-1)).left;
		int eright = ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.elementAt(CUP$CMinusParser$top-1)).right;
		ASTNode e = (ASTNode)((java_cup.runtime.Symbol) CUP$CMinusParser$stack.elementAt(CUP$CMinusParser$top-1)).value;
		 RESULT = e; 
              CUP$CMinusParser$result = parser.getSymbolFactory().newSymbol("factor",25, ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.elementAt(CUP$CMinusParser$top-2)), ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.peek()), RESULT);
            }
          return CUP$CMinusParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 55: // factor ::= var 
            {
              ASTNode RESULT =null;
		int vleft = ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.peek()).left;
		int vright = ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.peek()).right;
		ASTNode v = (ASTNode)((java_cup.runtime.Symbol) CUP$CMinusParser$stack.peek()).value;
		 RESULT = v; 
              CUP$CMinusParser$result = parser.getSymbolFactory().newSymbol("factor",25, ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.peek()), RESULT);
            }
          return CUP$CMinusParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 56: // factor ::= call 
            {
              ASTNode RESULT =null;
		int cleft = ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.peek()).left;
		int cright = ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.peek()).right;
		ASTNode c = (ASTNode)((java_cup.runtime.Symbol) CUP$CMinusParser$stack.peek()).value;
		 RESULT = c; 
              CUP$CMinusParser$result = parser.getSymbolFactory().newSymbol("factor",25, ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.peek()), RESULT);
            }
          return CUP$CMinusParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 57: // factor ::= NUM 
            {
              ASTNode RESULT =null;
		int nleft = ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.peek()).left;
		int nright = ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.peek()).right;
		String n = (String)((java_cup.runtime.Symbol) CUP$CMinusParser$stack.peek()).value;
		 RESULT = new ASTNode("NUM", n); 
              CUP$CMinusParser$result = parser.getSymbolFactory().newSymbol("factor",25, ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.peek()), RESULT);
            }
          return CUP$CMinusParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 58: // call ::= ID LPAREN args RPAREN 
            {
              ASTNode RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.elementAt(CUP$CMinusParser$top-3)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.elementAt(CUP$CMinusParser$top-3)).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$CMinusParser$stack.elementAt(CUP$CMinusParser$top-3)).value;
		int aleft = ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.elementAt(CUP$CMinusParser$top-1)).left;
		int aright = ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.elementAt(CUP$CMinusParser$top-1)).right;
		ASTNode a = (ASTNode)((java_cup.runtime.Symbol) CUP$CMinusParser$stack.elementAt(CUP$CMinusParser$top-1)).value;
		 RESULT = new ASTNode("CALL", id).addChild(a); 
              CUP$CMinusParser$result = parser.getSymbolFactory().newSymbol("call",26, ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.elementAt(CUP$CMinusParser$top-3)), ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.peek()), RESULT);
            }
          return CUP$CMinusParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 59: // args ::= arg_list 
            {
              ASTNode RESULT =null;
		int alleft = ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.peek()).left;
		int alright = ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.peek()).right;
		ASTNode al = (ASTNode)((java_cup.runtime.Symbol) CUP$CMinusParser$stack.peek()).value;
		 RESULT = al; 
              CUP$CMinusParser$result = parser.getSymbolFactory().newSymbol("args",27, ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.peek()), RESULT);
            }
          return CUP$CMinusParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 60: // args ::= 
            {
              ASTNode RESULT =null;
		 RESULT = new ASTNode("ARGS"); 
              CUP$CMinusParser$result = parser.getSymbolFactory().newSymbol("args",27, ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.peek()), RESULT);
            }
          return CUP$CMinusParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 61: // arg_list ::= arg_list COMMA expression 
            {
              ASTNode RESULT =null;
		int alleft = ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.elementAt(CUP$CMinusParser$top-2)).left;
		int alright = ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.elementAt(CUP$CMinusParser$top-2)).right;
		ASTNode al = (ASTNode)((java_cup.runtime.Symbol) CUP$CMinusParser$stack.elementAt(CUP$CMinusParser$top-2)).value;
		int eleft = ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.peek()).right;
		ASTNode e = (ASTNode)((java_cup.runtime.Symbol) CUP$CMinusParser$stack.peek()).value;
		 RESULT = al.addChild(e); 
              CUP$CMinusParser$result = parser.getSymbolFactory().newSymbol("arg_list",28, ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.elementAt(CUP$CMinusParser$top-2)), ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.peek()), RESULT);
            }
          return CUP$CMinusParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 62: // arg_list ::= expression 
            {
              ASTNode RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.peek()).right;
		ASTNode e = (ASTNode)((java_cup.runtime.Symbol) CUP$CMinusParser$stack.peek()).value;
		 RESULT = new ASTNode("ARGS").addChild(e); 
              CUP$CMinusParser$result = parser.getSymbolFactory().newSymbol("arg_list",28, ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$CMinusParser$stack.peek()), RESULT);
            }
          return CUP$CMinusParser$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number "+CUP$CMinusParser$act_num+"found in internal parse table");

        }
    } /* end of method */

  /** Method splitting the generated action code into several parts. */
  public final java_cup.runtime.Symbol CUP$CMinusParser$do_action(
    int                        CUP$CMinusParser$act_num,
    java_cup.runtime.lr_parser CUP$CMinusParser$parser,
    java.util.Stack            CUP$CMinusParser$stack,
    int                        CUP$CMinusParser$top)
    throws java.lang.Exception
    {
              return CUP$CMinusParser$do_action_part00000000(
                               CUP$CMinusParser$act_num,
                               CUP$CMinusParser$parser,
                               CUP$CMinusParser$stack,
                               CUP$CMinusParser$top);
    }
}

}
