
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20150326 (SVN rev 63)
//----------------------------------------------------

/** CUP generated interface containing symbol constants. */
public interface Sym {
  /* terminals */
  public static final int RBRACK = 9;
  public static final int ELSE = 24;
  public static final int SEMICOLON = 21;
  public static final int PLUS = 10;
  public static final int INT = 23;
  public static final int RPAREN = 5;
  public static final int EQUAL = 18;
  public static final int WHILE = 28;
  public static final int NOTEQUAL = 19;
  public static final int STAR = 12;
  public static final int SLASH = 13;
  public static final int LBRACK = 8;
  public static final int RETURN = 26;
  public static final int GREATERTHANEQ = 17;
  public static final int IF = 25;
  public static final int LPAREN = 4;
  public static final int ID = 2;
  public static final int NUM = 3;
  public static final int RBRAC = 7;
  public static final int COMMA = 22;
  public static final int LESSTHAN = 14;
  public static final int EOF = 0;
  public static final int LESSTHANEQ = 15;
  public static final int MINUS = 11;
  public static final int error = 1;
  public static final int ASSIGN = 20;
  public static final int LBRAC = 6;
  public static final int VOID = 27;
  public static final int GREATERTHAN = 16;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "ID",
  "NUM",
  "LPAREN",
  "RPAREN",
  "LBRAC",
  "RBRAC",
  "LBRACK",
  "RBRACK",
  "PLUS",
  "MINUS",
  "STAR",
  "SLASH",
  "LESSTHAN",
  "LESSTHANEQ",
  "GREATERTHAN",
  "GREATERTHANEQ",
  "EQUAL",
  "NOTEQUAL",
  "ASSIGN",
  "SEMICOLON",
  "COMMA",
  "INT",
  "ELSE",
  "IF",
  "RETURN",
  "VOID",
  "WHILE"
  };
}

