package old;
public enum TokenType {
  ID, NUM,
  LPAREN, RPAREN, LBRAC, RBRAC, LBRACK, RBRACK, COMMENT,
  PLUS, MINUS, STAR, SLASH, LESSTHAN, LESSTHANEQ, GREATERTHAN, GREATERTHANEQ, EQUAL, NOTEQUAL, ASSIGN,
  SEMICOLON, COMMA,
  INT, ELSE, IF, RETURN, VOID, WHILE,
  EOF, ERROR
}