
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20150326 (SVN rev 63)
//----------------------------------------------------

import java_cup.runtime.Symbol;
import java_cup.runtime.XMLElement;

/** CUP v0.11b 20150326 (SVN rev 63) generated parser.
  */
@SuppressWarnings({"rawtypes"})
public class CalcParser extends java_cup.runtime.lr_parser {

 public final Class getSymbolContainer() {
    return sym.class;
}

  /** Default constructor. */
  @Deprecated
  public CalcParser() {super();}

  /** Constructor which sets the default scanner. */
  @Deprecated
  public CalcParser(java_cup.runtime.Scanner s) {super(s);}

  /** Constructor which sets the default scanner. */
  public CalcParser(java_cup.runtime.Scanner s, java_cup.runtime.SymbolFactory sf) {super(s,sf);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\015\000\002\002\004\000\002\002\005\000\002\002" +
    "\005\000\002\002\003\000\002\003\005\000\002\003\005" +
    "\000\002\003\005\000\002\003\003\000\002\004\005\000" +
    "\002\004\003\000\002\005\005\000\002\005\003\000\002" +
    "\005\003" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\027\000\010\004\010\014\012\015\011\001\002\000" +
    "\020\002\ufffe\005\ufffe\006\ufffe\007\ufffe\010\020\011\022" +
    "\012\021\001\002\000\022\002\ufff8\005\ufff8\006\ufff8\007" +
    "\ufff8\010\ufff8\011\ufff8\012\ufff8\013\ufff8\001\002\000\010" +
    "\002\031\006\015\007\016\001\002\000\022\002\ufffa\005" +
    "\ufffa\006\ufffa\007\ufffa\010\ufffa\011\ufffa\012\ufffa\013\024" +
    "\001\002\000\010\004\010\014\012\015\011\001\002\000" +
    "\022\002\ufff5\005\ufff5\006\ufff5\007\ufff5\010\ufff5\011\ufff5" +
    "\012\ufff5\013\ufff5\001\002\000\022\002\ufff6\005\ufff6\006" +
    "\ufff6\007\ufff6\010\ufff6\011\ufff6\012\ufff6\013\ufff6\001\002" +
    "\000\010\005\014\006\015\007\016\001\002\000\022\002" +
    "\ufff7\005\ufff7\006\ufff7\007\ufff7\010\ufff7\011\ufff7\012\ufff7" +
    "\013\ufff7\001\002\000\010\004\010\014\012\015\011\001" +
    "\002\000\010\004\010\014\012\015\011\001\002\000\020" +
    "\002\uffff\005\uffff\006\uffff\007\uffff\010\020\011\022\012" +
    "\021\001\002\000\010\004\010\014\012\015\011\001\002" +
    "\000\010\004\010\014\012\015\011\001\002\000\010\004" +
    "\010\014\012\015\011\001\002\000\022\002\ufffc\005\ufffc" +
    "\006\ufffc\007\ufffc\010\ufffc\011\ufffc\012\ufffc\013\024\001" +
    "\002\000\010\004\010\014\012\015\011\001\002\000\022" +
    "\002\ufff9\005\ufff9\006\ufff9\007\ufff9\010\ufff9\011\ufff9\012" +
    "\ufff9\013\024\001\002\000\022\002\ufffb\005\ufffb\006\ufffb" +
    "\007\ufffb\010\ufffb\011\ufffb\012\ufffb\013\024\001\002\000" +
    "\022\002\ufffd\005\ufffd\006\ufffd\007\ufffd\010\ufffd\011\ufffd" +
    "\012\ufffd\013\024\001\002\000\020\002\000\005\000\006" +
    "\000\007\000\010\020\011\022\012\021\001\002\000\004" +
    "\002\001\001\002" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\027\000\012\002\005\003\003\004\006\005\004\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\012\002\012\003\003\004\006\005" +
    "\004\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\010\003\027\004\006\005" +
    "\004\001\001\000\010\003\016\004\006\005\004\001\001" +
    "\000\002\001\001\000\006\004\026\005\004\001\001\000" +
    "\006\004\025\005\004\001\001\000\006\004\022\005\004" +
    "\001\001\000\002\001\001\000\006\004\024\005\004\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$CalcParser$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
    {
      action_obj = new CUP$CalcParser$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$CalcParser$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 0;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}



  public static void main(String[] args) throws Exception {
    java.io.Reader r =
      (args.length == 0 || "-".equals(args[0]))
        ? new java.io.InputStreamReader(System.in)
        : new java.io.FileReader(args[0]);
    CalcLexerCup lx = new CalcLexerCup(r); // lexer “para CUP”
    CalcParser p = new CalcParser(lx);
    Double val = (Double) p.parse().value;
    System.out.println("RESULTADO = " + val);
  }


/** Cup generated class to encapsulate user supplied action code.*/
@SuppressWarnings({"rawtypes", "unchecked", "unused"})
class CUP$CalcParser$actions {
  private final CalcParser parser;

  /** Constructor */
  CUP$CalcParser$actions(CalcParser parser) {
    this.parser = parser;
  }

  /** Method 0 with the actual generated action code for actions 0 to 300. */
  public final java_cup.runtime.Symbol CUP$CalcParser$do_action_part00000000(
    int                        CUP$CalcParser$act_num,
    java_cup.runtime.lr_parser CUP$CalcParser$parser,
    java.util.Stack            CUP$CalcParser$stack,
    int                        CUP$CalcParser$top)
    throws java.lang.Exception
    {
      /* Symbol object for return from actions */
      java_cup.runtime.Symbol CUP$CalcParser$result;

      /* select the action based on the action number */
      switch (CUP$CalcParser$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // $START ::= E EOF 
            {
              Object RESULT =null;
		int start_valleft = ((java_cup.runtime.Symbol)CUP$CalcParser$stack.elementAt(CUP$CalcParser$top-1)).left;
		int start_valright = ((java_cup.runtime.Symbol)CUP$CalcParser$stack.elementAt(CUP$CalcParser$top-1)).right;
		Double start_val = (Double)((java_cup.runtime.Symbol) CUP$CalcParser$stack.elementAt(CUP$CalcParser$top-1)).value;
		RESULT = start_val;
              CUP$CalcParser$result = parser.getSymbolFactory().newSymbol("$START",0, ((java_cup.runtime.Symbol)CUP$CalcParser$stack.elementAt(CUP$CalcParser$top-1)), ((java_cup.runtime.Symbol)CUP$CalcParser$stack.peek()), RESULT);
            }
          /* ACCEPT */
          CUP$CalcParser$parser.done_parsing();
          return CUP$CalcParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // E ::= E PLUS T 
            {
              Double RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$CalcParser$stack.elementAt(CUP$CalcParser$top-2)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$CalcParser$stack.elementAt(CUP$CalcParser$top-2)).right;
		Double e1 = (Double)((java_cup.runtime.Symbol) CUP$CalcParser$stack.elementAt(CUP$CalcParser$top-2)).value;
		int tleft = ((java_cup.runtime.Symbol)CUP$CalcParser$stack.peek()).left;
		int tright = ((java_cup.runtime.Symbol)CUP$CalcParser$stack.peek()).right;
		Double t = (Double)((java_cup.runtime.Symbol) CUP$CalcParser$stack.peek()).value;
		 RESULT = e1 + t; 
              CUP$CalcParser$result = parser.getSymbolFactory().newSymbol("E",0, ((java_cup.runtime.Symbol)CUP$CalcParser$stack.elementAt(CUP$CalcParser$top-2)), ((java_cup.runtime.Symbol)CUP$CalcParser$stack.peek()), RESULT);
            }
          return CUP$CalcParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 2: // E ::= E MINUS T 
            {
              Double RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$CalcParser$stack.elementAt(CUP$CalcParser$top-2)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$CalcParser$stack.elementAt(CUP$CalcParser$top-2)).right;
		Double e1 = (Double)((java_cup.runtime.Symbol) CUP$CalcParser$stack.elementAt(CUP$CalcParser$top-2)).value;
		int tleft = ((java_cup.runtime.Symbol)CUP$CalcParser$stack.peek()).left;
		int tright = ((java_cup.runtime.Symbol)CUP$CalcParser$stack.peek()).right;
		Double t = (Double)((java_cup.runtime.Symbol) CUP$CalcParser$stack.peek()).value;
		 RESULT = e1 - t; 
              CUP$CalcParser$result = parser.getSymbolFactory().newSymbol("E",0, ((java_cup.runtime.Symbol)CUP$CalcParser$stack.elementAt(CUP$CalcParser$top-2)), ((java_cup.runtime.Symbol)CUP$CalcParser$stack.peek()), RESULT);
            }
          return CUP$CalcParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 3: // E ::= T 
            {
              Double RESULT =null;
		int tleft = ((java_cup.runtime.Symbol)CUP$CalcParser$stack.peek()).left;
		int tright = ((java_cup.runtime.Symbol)CUP$CalcParser$stack.peek()).right;
		Double t = (Double)((java_cup.runtime.Symbol) CUP$CalcParser$stack.peek()).value;
		 RESULT = t;     
              CUP$CalcParser$result = parser.getSymbolFactory().newSymbol("E",0, ((java_cup.runtime.Symbol)CUP$CalcParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$CalcParser$stack.peek()), RESULT);
            }
          return CUP$CalcParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 4: // T ::= T STAR P 
            {
              Double RESULT =null;
		int t1left = ((java_cup.runtime.Symbol)CUP$CalcParser$stack.elementAt(CUP$CalcParser$top-2)).left;
		int t1right = ((java_cup.runtime.Symbol)CUP$CalcParser$stack.elementAt(CUP$CalcParser$top-2)).right;
		Double t1 = (Double)((java_cup.runtime.Symbol) CUP$CalcParser$stack.elementAt(CUP$CalcParser$top-2)).value;
		int pleft = ((java_cup.runtime.Symbol)CUP$CalcParser$stack.peek()).left;
		int pright = ((java_cup.runtime.Symbol)CUP$CalcParser$stack.peek()).right;
		Double p = (Double)((java_cup.runtime.Symbol) CUP$CalcParser$stack.peek()).value;
		 RESULT = t1 * p; 
              CUP$CalcParser$result = parser.getSymbolFactory().newSymbol("T",1, ((java_cup.runtime.Symbol)CUP$CalcParser$stack.elementAt(CUP$CalcParser$top-2)), ((java_cup.runtime.Symbol)CUP$CalcParser$stack.peek()), RESULT);
            }
          return CUP$CalcParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 5: // T ::= T SLASH P 
            {
              Double RESULT =null;
		int t1left = ((java_cup.runtime.Symbol)CUP$CalcParser$stack.elementAt(CUP$CalcParser$top-2)).left;
		int t1right = ((java_cup.runtime.Symbol)CUP$CalcParser$stack.elementAt(CUP$CalcParser$top-2)).right;
		Double t1 = (Double)((java_cup.runtime.Symbol) CUP$CalcParser$stack.elementAt(CUP$CalcParser$top-2)).value;
		int pleft = ((java_cup.runtime.Symbol)CUP$CalcParser$stack.peek()).left;
		int pright = ((java_cup.runtime.Symbol)CUP$CalcParser$stack.peek()).right;
		Double p = (Double)((java_cup.runtime.Symbol) CUP$CalcParser$stack.peek()).value;
		 RESULT = t1 / p; 
              CUP$CalcParser$result = parser.getSymbolFactory().newSymbol("T",1, ((java_cup.runtime.Symbol)CUP$CalcParser$stack.elementAt(CUP$CalcParser$top-2)), ((java_cup.runtime.Symbol)CUP$CalcParser$stack.peek()), RESULT);
            }
          return CUP$CalcParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 6: // T ::= T INT_DIV P 
            {
              Double RESULT =null;
		int t1left = ((java_cup.runtime.Symbol)CUP$CalcParser$stack.elementAt(CUP$CalcParser$top-2)).left;
		int t1right = ((java_cup.runtime.Symbol)CUP$CalcParser$stack.elementAt(CUP$CalcParser$top-2)).right;
		Double t1 = (Double)((java_cup.runtime.Symbol) CUP$CalcParser$stack.elementAt(CUP$CalcParser$top-2)).value;
		int pleft = ((java_cup.runtime.Symbol)CUP$CalcParser$stack.peek()).left;
		int pright = ((java_cup.runtime.Symbol)CUP$CalcParser$stack.peek()).right;
		Double p = (Double)((java_cup.runtime.Symbol) CUP$CalcParser$stack.peek()).value;
		 RESULT = Math.floor(t1 / p); 
              CUP$CalcParser$result = parser.getSymbolFactory().newSymbol("T",1, ((java_cup.runtime.Symbol)CUP$CalcParser$stack.elementAt(CUP$CalcParser$top-2)), ((java_cup.runtime.Symbol)CUP$CalcParser$stack.peek()), RESULT);
            }
          return CUP$CalcParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 7: // T ::= P 
            {
              Double RESULT =null;
		int pleft = ((java_cup.runtime.Symbol)CUP$CalcParser$stack.peek()).left;
		int pright = ((java_cup.runtime.Symbol)CUP$CalcParser$stack.peek()).right;
		Double p = (Double)((java_cup.runtime.Symbol) CUP$CalcParser$stack.peek()).value;
		 RESULT = p; 
              CUP$CalcParser$result = parser.getSymbolFactory().newSymbol("T",1, ((java_cup.runtime.Symbol)CUP$CalcParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$CalcParser$stack.peek()), RESULT);
            }
          return CUP$CalcParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 8: // P ::= P POW P 
            {
              Double RESULT =null;
		int p1left = ((java_cup.runtime.Symbol)CUP$CalcParser$stack.elementAt(CUP$CalcParser$top-2)).left;
		int p1right = ((java_cup.runtime.Symbol)CUP$CalcParser$stack.elementAt(CUP$CalcParser$top-2)).right;
		Double p1 = (Double)((java_cup.runtime.Symbol) CUP$CalcParser$stack.elementAt(CUP$CalcParser$top-2)).value;
		int p2left = ((java_cup.runtime.Symbol)CUP$CalcParser$stack.peek()).left;
		int p2right = ((java_cup.runtime.Symbol)CUP$CalcParser$stack.peek()).right;
		Double p2 = (Double)((java_cup.runtime.Symbol) CUP$CalcParser$stack.peek()).value;
		 RESULT = Math.pow(p1, p2); 
              CUP$CalcParser$result = parser.getSymbolFactory().newSymbol("P",2, ((java_cup.runtime.Symbol)CUP$CalcParser$stack.elementAt(CUP$CalcParser$top-2)), ((java_cup.runtime.Symbol)CUP$CalcParser$stack.peek()), RESULT);
            }
          return CUP$CalcParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 9: // P ::= F 
            {
              Double RESULT =null;
		int fleft = ((java_cup.runtime.Symbol)CUP$CalcParser$stack.peek()).left;
		int fright = ((java_cup.runtime.Symbol)CUP$CalcParser$stack.peek()).right;
		Double f = (Double)((java_cup.runtime.Symbol) CUP$CalcParser$stack.peek()).value;
		 RESULT = f; 
              CUP$CalcParser$result = parser.getSymbolFactory().newSymbol("P",2, ((java_cup.runtime.Symbol)CUP$CalcParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$CalcParser$stack.peek()), RESULT);
            }
          return CUP$CalcParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 10: // F ::= LPAREN E RPAREN 
            {
              Double RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$CalcParser$stack.elementAt(CUP$CalcParser$top-1)).left;
		int eright = ((java_cup.runtime.Symbol)CUP$CalcParser$stack.elementAt(CUP$CalcParser$top-1)).right;
		Double e = (Double)((java_cup.runtime.Symbol) CUP$CalcParser$stack.elementAt(CUP$CalcParser$top-1)).value;
		 RESULT = e; 
              CUP$CalcParser$result = parser.getSymbolFactory().newSymbol("F",3, ((java_cup.runtime.Symbol)CUP$CalcParser$stack.elementAt(CUP$CalcParser$top-2)), ((java_cup.runtime.Symbol)CUP$CalcParser$stack.peek()), RESULT);
            }
          return CUP$CalcParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 11: // F ::= INT 
            {
              Double RESULT =null;
		int ileft = ((java_cup.runtime.Symbol)CUP$CalcParser$stack.peek()).left;
		int iright = ((java_cup.runtime.Symbol)CUP$CalcParser$stack.peek()).right;
		Integer i = (Integer)((java_cup.runtime.Symbol) CUP$CalcParser$stack.peek()).value;
		 RESULT = i.doubleValue(); 
              CUP$CalcParser$result = parser.getSymbolFactory().newSymbol("F",3, ((java_cup.runtime.Symbol)CUP$CalcParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$CalcParser$stack.peek()), RESULT);
            }
          return CUP$CalcParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 12: // F ::= FLOAT 
            {
              Double RESULT =null;
		int dleft = ((java_cup.runtime.Symbol)CUP$CalcParser$stack.peek()).left;
		int dright = ((java_cup.runtime.Symbol)CUP$CalcParser$stack.peek()).right;
		Double d = (Double)((java_cup.runtime.Symbol) CUP$CalcParser$stack.peek()).value;
		 RESULT = d; 
              CUP$CalcParser$result = parser.getSymbolFactory().newSymbol("F",3, ((java_cup.runtime.Symbol)CUP$CalcParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$CalcParser$stack.peek()), RESULT);
            }
          return CUP$CalcParser$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number "+CUP$CalcParser$act_num+"found in internal parse table");

        }
    } /* end of method */

  /** Method splitting the generated action code into several parts. */
  public final java_cup.runtime.Symbol CUP$CalcParser$do_action(
    int                        CUP$CalcParser$act_num,
    java_cup.runtime.lr_parser CUP$CalcParser$parser,
    java.util.Stack            CUP$CalcParser$stack,
    int                        CUP$CalcParser$top)
    throws java.lang.Exception
    {
              return CUP$CalcParser$do_action_part00000000(
                               CUP$CalcParser$act_num,
                               CUP$CalcParser$parser,
                               CUP$CalcParser$stack,
                               CUP$CalcParser$top);
    }
}

}
