
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20150326 (SVN rev 63)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int MINUS = 5;
  public static final int INT = 10;
  public static final int SLASH = 7;
  public static final int POW = 9;
  public static final int INT_DIV = 8;
  public static final int STAR = 6;
  public static final int EOF = 0;
  public static final int PLUS = 4;
  public static final int error = 1;
  public static final int RPAREN = 3;
  public static final int LPAREN = 2;
  public static final int FLOAT = 11;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "LPAREN",
  "RPAREN",
  "PLUS",
  "MINUS",
  "STAR",
  "SLASH",
  "INT_DIV",
  "POW",
  "INT",
  "FLOAT"
  };
}

